;;; Blocked notes for deptree-resolver-260417ao
;;; 24 packages remain BLOCKED after exhaustive evaluation
;;;
;;; ttf-ms-office365 (#16018): PROPRIETARY_LICENSE: Microsoft Office fonts with redistribution prohibition.  Tried: (1) license LicenseRef-ms-office-2024 prohibits redistribution; (2) no direct download without MS Office license; (3) cannot legally include in channel
;;; fonts-apple (#14971): PROPRIETARY_LICENSE: Apple restricted font license forbids redistribution.  Tried: (1) custom:apple-restricted-font license terms prohibit redistribution; (2) no free alternative with same glyphs; (3) cannot legally include in channel
;;; otf-apple-pingfang (#15346): PROPRIETARY_LICENSE: Apple PingFang font with restricted redistribution.  Tried: (1) same apple-restricted-font license; (2) no free redistribution allowed; (3) cannot include in channel
;;; otf-apple-pingfang-relaxed (#15347): PROPRIETARY_LICENSE: Apple PingFang variant with restricted license.  Tried: (1) same apple-restricted-font; (2) no free redistribution; (3) cannot include
;;; otf-apple-pingfang-ui (#15348): PROPRIETARY_LICENSE: Apple PingFang UI variant with restricted license.  Tried: (1) same apple-restricted-font; (2) no free redistribution; (3) cannot include
;;; code-server-marketplace (#15031): MISSING_DEPENDENCY: Requires code-server (complex Node.js app not in Guix).  Tried: (1) package is a JSON patch for code-server product.json; (2) code-server has standalone binary but packaging it is a separate effort; (3) $EXTENSIONS_GALLERY env var provides equivalent functionality without patching
;;; libfprint-2-tod1-broadcom (#15005): PROPRIETARY_LICENSE: Dell/Broadcom proprietary binary fingerprint driver blob.  Tried: (1) PPA has .so binary blobs, proprietary license; (2) depends on libfprint-tod not in Guix; (3) no source code available
;;; ntsync-dkms (#15010): DKMS_UNSUPPORTED: Out-of-tree DKMS kernel module; already upstream in Linux >= 6.14.  Tried: (1) DKMS not supported in Guix; (2) users with kernel >= 6.14 have it built-in; (3) out-of-tree module packaging impossible without DKMS
;;; odoo18-nightly (#14669): MASSIVE_SCALE: Odoo 18 ERP with 500+ Python dependencies.  Tried: (1) Python dep tree (500+) exceeds practical manual packaging; (2) nightly versioning breaks reproducibility; (3) PostgreSQL service integration requires system design
;;; arch-shell (#14726): ARCH_SPECIFIC: Creates Arch chroots using devtools; no cross-distro utility.  Tried: (1) depends on devtools (Arch-only); (2) Guix has own container/profile mechanisms; (3) no upstream portability interest
;;; dude-bin (#14699): ARCH_SPECIFIC: Rust binary linking against libalpm (pacman library).  Tried: (1) libalpm not in Guix and Arch-only; (2) guix gc --delete-generations provides native equivalent; (3) no portable alternative exists
;;; mt76-dkms-git (#14914): DKMS_UNSUPPORTED: DKMS kernel module; mt76 driver already upstream in Linux kernel.  Tried: (1) DKMS not supported in Guix; (2) mt76 already in kernel; (3) users should use kernel built-in mt76
;;; parus (#15189): ARCH_SPECIFIC: TUI for paru (Arch AUR helper); no utility outside Arch.  Tried: (1) depends on paru (Arch-only); (2) depends on skim; (3) no cross-distro utility
;;; pacwall-git (#14584): ARCH_SPECIFIC: Dependency wallpaper generator querying pacman database exclusively.  Tried: (1) core logic uses pacman -Qi; (2) rewrite for Guix requires complete fork; (3) guix graph provides native alternative
;;; starsector (#15139): PROPRIETARY_LICENSE: Commercial game requiring paid license.  Tried: (1) AUR PKGBUILD expects user-provided installer; (2) no free download available; (3) license prohibits redistribution
;;; asp (#14587): ARCH_SPECIFIC + DEPRECATED: Arch Build System tool replaced by pkgctl.  Tried: (1) requires Arch SVN infrastructure; (2) Guix has own source management; (3) no cross-distro utility
;;; deemix-gui-appimage (#14759): LEGAL_ISSUES + SOURCE_UNAVAILABLE: Deezer music downloader archived after legal action.  Tried: (1) project taken down by maintainers; (2) no stable source URL remains; (3) legal risk for redistribution
;;; gdrcopy (#15131): COMPLEX_DEPS: NVIDIA GPU Direct RDMA requiring proprietary kernel modules.  Tried: (1) NVIDIA kernel modules not in Guix; (2) userspace library useless without gdrdrv; (3) HPC/CUDA workloads incompatible with Guix sandbox
;;; brother-mfc-j5720dw (#15008): PROPRIETARY_LICENSE + ARCH_SPECIFIC: Brother proprietary printer driver with i386 binary blobs.  Tried: (1) contains i386 binaries requiring lib32-glibc; (2) lib32-glibc not in Guix; (3) proprietary license
;;; devkitty-git (#15058): NO_LINUX_BINARY: Only macOS releases published; requires Electron 41 not in Guix.  Tried: (1) all 90+ releases are macOS-only; (2) build from source needs npm/pnpm/nvm + Electron 41; (3) Electron 41 not in Guix; electron-builder.yml only defines mac target
;;; xilinx-ise (#14616): PROPRIETARY_LICENSE: Registration-walled 6GB+ installer requiring Xilinx EULA.  Tried: (1) no direct download URL; (2) requires account + EULA acceptance; (3) depends on legacy Qt4 + gcc49 not in Guix
;;; python-torchaudio-rocm (#14583): COMPLEX_DEPS: PyTorch audio with ROCm/HIP GPU support; massive dep chain.  Tried: (1) ROCm ecosystem (100+ packages) not in Guix; (2) rocm-hip-sdk not available; (3) CPU-only variant loses purpose of ROCm package
;;; godot-double-mono (#14495): DOTNET_UNSUPPORTED: No prebuilt double+mono binary exists anywhere; requires dotnet-sdk-8.0.  Tried: (1) official releases have standard mono but not double+mono; (2) no community builds exist; (3) build from source requires dotnet-sdk-8.0 not in Guix
;;; aiot-ide (#15062): PROPRIETARY_LICENSE: Xiaomi proprietary IoT IDE with no public download.  Tried: (1) iot.mi.com requires Chinese account; (2) proprietary custom license; (3) no direct download URL
