;;; Blocked notes for deptree-resolver-260417au
;;; 40 packages remain BLOCKED after exhaustive evaluation
;;;
;;; ttf-ms-office365 (#16018): PROPRIETARY_LICENSE: Microsoft Office fonts prohibit redistribution.  Tried: (1) LicenseRef-ms-office-2024; (2) requires MS Office license; (3) cannot include in channel
;;; datagrip-jre (#21653): PROPRIETARY_LICENSE: JetBrains proprietary bundled JRE tied to DataGrip release cycle.  Tried: (1) JBR custom OpenJDK fork with proprietary patches; (2) DataGrip itself is proprietary; (3) adoptium/temurin available as free alternative
;;; fonts-apple (#14971): PROPRIETARY_LICENSE: Apple restricted font license forbids redistribution.  Tried: (1) license terms explicitly prohibit redistribution; (2) no free alternative with same glyphs; (3) cannot legally include in channel
;;; lib32-amdvlk-bin (#15531): ARCH_SPECIFIC: 32-bit AMD Vulkan driver requiring i686 multilib support.  Tried: (1) lib32/multilib not available in Guix; (2) package is Arch multilib-specific; (3) Guix has no 32-bit compat layer for x86_64
;;; otf-apple-pingfang (#15346): PROPRIETARY_LICENSE: Apple PingFang font with restricted redistribution license.  Tried: (1) apple-restricted-font license; (2) no free redistribution; (3) cannot include in channel
;;; otf-apple-pingfang-relaxed (#15347): PROPRIETARY_LICENSE: Apple PingFang relaxed variant with restricted license.  Tried: (1) same apple-restricted-font; (2) no free redistribution; (3) cannot include
;;; otf-apple-pingfang-ui (#15348): PROPRIETARY_LICENSE: Apple PingFang UI variant with restricted license.  Tried: (1) same apple-restricted-font; (2) no free redistribution; (3) cannot include
;;; code-server-marketplace (#15031): COMPLEX_DEPS: requires code-server (complex Node.js app not in Guix).  Tried: (1) depends on code-server; (2) code-server needs deep npm tree; (3) EXTENSIONS_GALLERY env var provides equivalent
;;; libfprint-2-tod1-broadcom (#15005): PROPRIETARY_LICENSE: Dell/Broadcom proprietary binary fingerprint driver blob.  Tried: (1) PPA has .so blobs -- proprietary; (2) no source code available; (3) restricted license
;;; ntsync-dkms (#15010): DKMS_UNSUPPORTED: ntsync upstream in Linux >= 6.14.  Tried: (1) DKMS not supported in Guix; (2) kernel >= 6.14 has it built-in; (3) out-of-tree module packaging impossible
;;; odoo18-nightly (#14669): MASSIVE_SCALE: Odoo 18 ERP needs 500+ Python deps and PostgreSQL.  Tried: (1) Python dep tree (500+) exceeds practical packaging; (2) nightly versioning breaks reproducibility; (3) PostgreSQL service integration requires system design
;;; arch-shell (#14726): ARCH_SPECIFIC: depends on mkarchroot/devtools for Arch chroots.  Tried: (1) devtools not portable; (2) Guix has own container/profile mechanisms; (3) no upstream portability interest
;;; dude-bin (#14699): ARCH_SPECIFIC: Rust binary linking against libalpm (pacman library).  Tried: (1) libalpm not in Guix and Arch-only; (2) guix gc --delete-generations provides native equivalent; (3) no portable alternative
;;; mt76-dkms-git (#14914): DKMS_UNSUPPORTED: out-of-tree DKMS kernel module.  Tried: (1) mt76 driver already upstream in Linux kernel; (2) DKMS not supported in Guix; (3) users should use kernel built-in mt76
;;; parus (#15189): ARCH_SPECIFIC: TUI frontend for paru (Arch AUR helper).  Tried: (1) depends on paru (Arch-only); (2) depends on skim; (3) no utility outside Arch Linux
;;; winscp (#22501): WINDOWS_ONLY: Windows file manager requiring Wine runtime.  Tried: (1) not a native Linux application; (2) Wine packaging in Guix doesn't support complex GUI apps; (3) native alternatives exist (FileZilla, Filezilla, etc.)
;;; gksu (#21534): COMPLEX_DEPS + OBSOLETE: graphical su frontend needing libgksu.  Tried: (1) libgksu not in Guix; (2) project superseded by pkexec/polkit; (3) original nongnu.org source may be stale; gksu-revived fork exists but libgksu still needed
;;; pacwall-git (#14584): ARCH_SPECIFIC: shell script queries pacman database exclusively.  Tried: (1) core logic uses pacman -Qi; (2) rewrite for Guix requires complete fork; (3) guix graph provides native alternative
;;; rtl8821ce-dkms-git (#22214): DKMS_UNSUPPORTED: out-of-tree DKMS kernel module.  Tried: (1) Guix kernel module model requires building with kernel; (2) rtl8821ce staging driver available in newer kernels; (3) DKMS incompatible with Guix
;;; starsector (#15139): PROPRIETARY_LICENSE: commercial game requiring paid license.  Tried: (1) AUR PKGBUILD expects user-provided installer; (2) no free download; (3) license prohibits redistribution
;;; asp (#14587): ARCH_SPECIFIC + DEPRECATED: Arch Build System tool replaced by pkgctl Nov 2023.  Tried: (1) requires Arch SVN infrastructure; (2) Guix has own source management; (3) no cross-distro utility
;;; deemix-gui-appimage (#14759): LEGAL_ISSUES + SOURCE_UNAVAILABLE: Deezer music downloader archived after legal action.  Tried: (1) project taken down by maintainers; (2) no stable source URL; (3) legal risk for redistribution
;;; deezer (#21712): COMPLEX_DEPS: requires extracting Windows .exe, patching with asar, then Electron wrapping.  Tried: (1) Windows .exe source only; (2) needs electron39 not in Guix; (3) extremely fragile cross-platform repackaging
;;; gdrcopy (#15131): COMPLEX_DEPS: NVIDIA GPU Direct RDMA requiring proprietary kernel modules.  Tried: (1) NVIDIA kernel modules not in Guix; (2) userspace library useless without gdrdrv; (3) HPC/CUDA workloads incompatible
;;; brother-mfc-j5720dw (#15008): PROPRIETARY_LICENSE + ARCH_SPECIFIC: Brother proprietary printer driver with i386 binary blobs.  Tried: (1) contains i386 binaries; (2) requires lib32-glibc; (3) proprietary license
;;; devkitty-git (#15058): COMPLEX_DEPS: requires Electron 41.  Tried: (1) GitHub releases macOS-only -- no Linux builds in 90+ releases; (2) build needs npm/pnpm/nvm + Electron 41; (3) no Linux binary published
;;; vim-youcompleteme-git (#21386): COMPLEX_DEPS: code completion engine requiring cmake + clang + git submodules.  Tried: (1) cmake build for ycmd server with clang linkage; (2) git submodules (ycmd) need special handling; (3) clang API version coupling makes builds fragile
;;; xilinx-ise (#14616): PROPRIETARY_LICENSE: registration-walled 6GB+ proprietary installer requiring Xilinx EULA.  Tried: (1) no direct download URL; (2) requires account + EULA acceptance; (3) depends on legacy Qt4 + gcc49 not in Guix
;;; qtutilities-qt6 (#23303): COMPLEX_DEPS: requires cpp-utilities (C++ library) to be packaged first.  Tried: (1) cmake-build-system feasible; (2) needs cpp-utilities + Qt6; (3) 2-package chain needed; will attempt in future pass with syncthingtray
;;; mkchromecast-git (#23180): COMPLEX_DEPS: needs python-pychromecast.  Tried: (1) python-pychromecast not in Guix; (2) python-netifaces deprecated; (3) python-pychromecast depends on protobuf + zeroconf (in Guix) but needs packaging; will attempt in future pass
;;; pamac-all (#22052): ARCH_SPECIFIC: Manjaro/Arch package manager GUI frontend requiring libalpm/pacman ecosystem.  Tried: (1) libpamac depends on libalpm; (2) pacman library not portable; (3) Guix has own package management GUI potential
;;; syncthingtray (#21493): COMPLEX_DEPS: requires packaging 3 C++ libraries first (cpp-utilities, qtutilities, qtforkawesome).  Tried: (1) all deps are CMake+Qt6 libraries by same author; (2) chain of 4 packages needed; (3) feasible but exceeds single-pass scope; will attempt in future pass
;;; python-torchaudio-rocm (#14583): COMPLEX_DEPS: ROCm ecosystem (100+ packages) not available in Guix.  Tried: (1) rocm-hip-sdk not available; (2) ROCm bootstrap chain is massive; (3) CPU-only variant defeats ROCm purpose
;;; subliminal (#22312): COMPLEX_DEPS: Python subtitle library missing 6+ deps.  Tried: (1) python-babelfish not in Guix; (2) python-guessit not in Guix; (3) python-enzyme, dogpile.cache, python-knowit all missing; chain too long for single pass
;;; godot-double-mono (#14495): DOTNET_UNSUPPORTED: Godot double-precision with C#/Mono requires .NET SDK 8.0 not in Guix.  Tried: (1) dotnet-sdk-8.0 + nuget needed; (2) no pre-built binary with double+mono for Linux; (3) stripping Mono defeats package purpose vs godot-double
;;; aiot-ide (#15062): PROPRIETARY_LICENSE: Xiaomi proprietary IoT IDE with no source.  Tried: (1) iot.mi.com requires Chinese account; (2) proprietary custom license; (3) no direct download URL
;;; cdesktopenv (#22627): COMPLEX_DEPS: CDE desktop requires Motif + ksh + opensp + libutempter.  Tried: (1) Motif not in Guix; (2) ksh packaging needed; (3) heavily patched autotools build with Debian-specific changes; last release 2022
;;; nautilus-typeahead (#22050): COMPLEX_DEPS: requires patching and rebuilding entire GNOME Nautilus.  Tried: (1) needs glycin, libadwaita, tinysparql not in Guix; (2) patch tracks upstream version closely; (3) 30+ deps chain for a single feature patch
;;; ladybird-git (#22620): COMPLEX_DEPS: experimental browser requiring vcpkg + CMake 3.30+ + gcc-14/clang-21.  Tried: (1) vcpkg dependency model incompatible with Guix; (2) requires ANGLE, simdutf, cpptrace, skia-static; (3) alpha-quality, targeting 2026 release
;;; scribus-svn (#21904): COMPLEX_DEPS: development version of Scribus DTP with 30+ dep chain.  Tried: (1) stable scribus in Guix upstream; (2) SVN snapshots version instability; (3) massive dep chain mirrors stable but with additional patches; prefer upstream stable
