;;; Blocked notes for deptree-resolver-260424a
;;; Timestamp: 2026-04-24T12:00:00+00:00
;;; 9 packages remain BLOCKED (2 resolved from 11)
;;;
;;; bakkesmod-steam (#17468): PLATFORM_UNSUPPORTED: Windows-only mod (Rocket League via Steam/Proton); no native Linux binary or source available. A1: searched for Linux port — none exists. A2: checked if wine/proton wrapper feasible — mod hooks into Windows game process. A3: checked for alternative Linux-native mods — none found.
;;; lib32-opencl-nvidia-390xx (#17502): MULTILIB_UNSUPPORTED: requires 32-bit NVIDIA 390xx legacy driver (lib32-zlib, lib32-gcc-libs); Guix lacks multilib support. A1: checked for 64-bit equivalent — nvidia-390xx is also legacy/unsupported. A2: checked if opencl-nvidia (current) could substitute — different driver series. A3: checked Guix multilib status — not supported, no workaround.
;;; clash-for-windows-chinese (#17433): LICENSE_REVIEW_NEEDED: Chinese fork at github.com/Z-Siqi/Clash-for-Windows_Chinese is active with Linux x64 builds, but repo has no license file/metadata; original Clash for Windows was proprietary. A1: confirmed source IS available (fork alive, has releases). A2: checked license — none declared in repo. A3: original project was proprietary; redistribution rights unclear.
;;; factorio-space-age-experimental (#17440): NON_DISTRIBUTABLE: commercial game requiring purchased license from factorio.com; EULA prohibits binary redistribution. A1: checked if open-source client exists — no. A2: checked if installer-only package feasible — requires user credentials. A3: confirmed EULA explicitly restricts distribution.
;;; capt-src (#17255): MULTILIB_UNSUPPORTED: Canon CAPT printer driver requires 32-bit filter binaries (lib32-libxml2-legacy, lib32-popt, lib32-gcc-libs, lib32-libcups, lib32-glibc); architecture fundamentally requires 32-bit components. A1: checked if 64-bit-only build possible — CAPT protocol uses 32-bit captfilter binary. A2: checked for alternative 64-bit Canon driver — CAPT is 32-bit only. A3: checked Guix multilib support — not available.
;;; python-jax-rocm (#17278): ROCM_DEPENDENCY: requires full AMD ROCm stack (miopen-hip, rccl, rocm-hip-runtime, rocm-hip-sdk, bazel). A1: checked if Guix has ROCm — not available. A2: checked if CPU fallback feasible — defeats purpose (python-jax without ROCm is the standard jax). A3: checked for partial ROCm packaging — too many components (dozens of packages).
;;; firestorm-next-bin (#17261): MULTILIB_UNSUPPORTED: prebuilt Second Life viewer requiring 32-bit libraries (lib32-libidn, lib32-libsndfile, lib32-util-linux, lib32-zlib). A1: checked for 64-bit binary — this binary release bundles 32-bit libs. A2: checked if building from source avoids 32-bit — Firestorm source build still needs 32-bit compatibility for SL protocol. A3: checked Guix multilib — not supported.
;;; etlegacy32-mod (#17424): MULTILIB_UNSUPPORTED: 32-bit game mod explicitly requiring lib32-* build deps (lib32-alsa-lib, lib32-curl, lib32-freetype2, lib32-sdl2, etc.). A1: checked for 64-bit etlegacy — exists as separate AUR package (etlegacy, not -32). A2: this specific package is the 32-bit mod variant — cannot be built without multilib. A3: confirmed Guix lacks multilib.
;;; ffmpeg-cuda-full (#17346): CUDA_DEPENDENCY: requires NVIDIA CUDA toolkit and nonfree codecs (libfdk-aac); depends on cuda, nvidia-utils, ffnvcodec-headers, amf-headers. A1: checked if Guix has CUDA — not available. A2: checked if non-CUDA build possible — defeats purpose (regular ffmpeg already in Guix). A3: license is 'custom:nonfree' due to libfdk-aac — non-distributable even without CUDA.
