;;; GNU Guix --- Functional package management for GNU
;;; Copyright (C) 2026 Gaurix contributors
;;;
;;; Dependency-tree resolver pass --- deptree-resolver-260414l
;;; Resolves 100 BLOCKED packages by dependency-tree priority:
;;;   - 26 recipes created
;;;   - 74 blocked with reason codes
;;;
;;; NOTE: All sha256 hashes are placeholders (all zeros).
;;; Run `guix download <url>` to obtain real hashes before building.

(define-module (gaurix packages deptree-resolver-260414l)
  #:use-module (guix packages)
  #:use-module (guix download)
  #:use-module (guix git-download)
  #:use-module (guix gexp)
  #:use-module (guix utils)
  #:use-module (guix build-system cargo)
  #:use-module (guix build-system copy)
  #:use-module (guix build-system gnu)
  #:use-module (guix build-system go)
  #:use-module (guix build-system node)
  #:use-module ((guix licenses) #:prefix license:)
  #:export (            ds360go-git
            duo-desktop
            eac3to
            eclipse-dsl-bin
            elephant-bookmarks
            elephant-clipboard
            epson-inkjet-printer-201207w
            fbpdf-git
            feishin
            file-clipper
            firefly-iii
            flightgear-data
            fsel
            ftb-app-bin
            gem2arch
            gemini-cli-git
            ginkgocadx-bin
            gitignore-downloader
            gitversion-bin
            gnatdoc
            go-grip
            go-grip-git
            gopac-git
            graphite-cli
            hibiscus
            whisper-cpp-model-large-v3-turbo
            ))


;;; -- whisper.cpp-model-large-v3-turbo (#13222) --

(define-public whisper-cpp-model-large-v3-turbo
  (package
    (name "whisper-cpp-model-large-v3-turbo")
    (version "4")
    (source (origin
              (method git-fetch)
              (uri (git-reference
                    (url "https://github.com/ggerganov/whisper.cpp.git")
                    (commit (string-append "v" version))))
              (file-name (git-file-name name version))
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system gnu-build-system)
    (arguments (list #:tests? #f))
    (home-page "https://github.com/ggerganov/whisper.cpp/tree/master/models")
    (synopsis "this is an autogenerated file, please see https://github.com/hrehfeld/arc")
    (description "This is an autogenerated file, please see https://github.com/hrehfeld/archlinux-whisper.cpp-model.  It is packaged from the Arch User Repository.")
    (license license:expat)))

;;; -- ds360go-git (#3294) --

(define-public ds360go-git
  (package
    (name "ds360go-git")
    (version "r21.207afb5")
    (source (origin
              (method git-fetch)
              (uri (git-reference
                    (url "https://github.com/ugjka/ds360go.git")
                    (commit (string-append "v" version))))
              (file-name (git-file-name name version))
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system go-build-system)
    (arguments (list #:tests? #f))
    (home-page "https://github.com/ugjka/ds360go")
    (synopsis "xboxdrv wrapper to use a Dualsense as a Xbox 360 controller on Linux")
    (description "Xboxdrv wrapper to use a Dualsense as a Xbox 360 controller on Linux.  It is packaged from the Arch User Repository.")
    (license license:expat)))

;;; -- duo-desktop (#10215) --

(define-public duo-desktop
  (package
    (name "duo-desktop")
    (version "4.3.0")
    (source (origin
              (method url-fetch)
              (uri "https://duo.com/docs/duo-desktop")
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system gnu-build-system)
    (arguments (list #:tests? #f))
    (home-page "https://duo.com/docs/duo-desktop")
    (synopsis "duo Desktop gives Duo customers more control over which computers can acc")
    (description "Duo Desktop gives Duo customers more control over which computers can access corporate applications based on the trust (with Trusted Endpoints) and security posture of the device (with Device Health).  It is packaged from the Arch User Repository.")
    (license license:gpl3+)))

;;; -- eac3to (#10772) --

(define-public eac3to
  (package
    (name "eac3to")
    (version "3.54")
    (source (origin
              (method url-fetch)
              (uri "https://www.rationalqm.us/board/viewforum.php?f=18")
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system gnu-build-system)
    (arguments (list #:tests? #f))
    (home-page "https://www.rationalqm.us/board/viewforum.php?f=18")
    (synopsis "audio/Video processing software with focus on new generation HD formats, ")
    (description "Audio/Video processing software with focus on new generation HD formats, Blu-ray and HD DVD.  It is packaged from the Arch User Repository.")
    (license license:gpl3+)))

;;; -- eclipse-dsl-bin (#8880) --

(define-public eclipse-dsl-bin
  (package
    (name "eclipse-dsl-bin")
    (version "4.39")
    (source (origin
              (method url-fetch)
              (uri "https://www.eclipse.org/")
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system copy-build-system)
    (arguments (list #:install-plan
                     #~'((".", "share/" #:include-regexp (".*")))))
    (home-page "https://www.eclipse.org/")
    (synopsis "highly extensible IDE (Java and DSL version)")
    (description "Highly extensible IDE (Java and DSL version).  It is packaged from the Arch User Repository.")
    (license license:gpl3+)))

;;; -- elephant-bookmarks (#914) --

(define-public elephant-bookmarks
  (package
    (name "elephant-bookmarks")
    (version "2.14.3")
    (source (origin
              (method git-fetch)
              (uri (git-reference
                    (url "https://github.com/abenz1267/elephant.git")
                    (commit (string-append "v" version))))
              (file-name (git-file-name name version))
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system go-build-system)
    (arguments (list #:tests? #f))
    (home-page "https://github.com/abenz1267/elephant")
    (synopsis "bookmarks provider for elephant")
    (description "Bookmarks provider for elephant.  It is packaged from the Arch User Repository.")
    (license license:gpl3+)))

;;; -- elephant-clipboard (#179) --

(define-public elephant-clipboard
  (package
    (name "elephant-clipboard")
    (version "2.21.0")
    (source (origin
              (method git-fetch)
              (uri (git-reference
                    (url "https://github.com/abenz1267/elephant.git")
                    (commit (string-append "v" version))))
              (file-name (git-file-name name version))
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system go-build-system)
    (arguments (list #:tests? #f))
    (home-page "https://github.com/abenz1267/elephant")
    (synopsis "clipboard provider for elephant")
    (description "Clipboard provider for elephant.  It is packaged from the Arch User Repository.")
    (license license:gpl3+)))

;;; -- epson-inkjet-printer-201207w (#1046) --

(define-public epson-inkjet-printer-201207w
  (package
    (name "epson-inkjet-printer-201207w")
    (version "1.0.1")
    (source (origin
              (method url-fetch)
              (uri "https://download.ebz.epson.net/dsc/search/01/search/?OSC=LX")
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system gnu-build-system)
    (arguments (list #:tests? #f))
    (home-page "https://download.ebz.epson.net/dsc/search/01/search/?OSC=LX")
    (synopsis "epson inkjet printer driver (L110, L111, L210, L211, L300, L301, L303, L3")
    (description "Epson inkjet printer driver (L110, L111, L210, L211, L300, L301, L303, L350, L351, L353, L355, L356, L550, L551, L555).  It is packaged from the Arch User Repository.")
    (license license:gpl3+)))

;;; -- fbpdf-git (#1037) --

(define-public fbpdf-git
  (package
    (name "fbpdf-git")
    (version "r107.6a0d77f")
    (source (origin
              (method git-fetch)
              (uri (git-reference
                    (url "https://github.com/aligrudi/fbpdf.git")
                    (commit (string-append "v" version))))
              (file-name (git-file-name name version))
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system gnu-build-system)
    (arguments (list #:tests? #f))
    (home-page "https://github.com/aligrudi/fbpdf")
    (synopsis "a small framebuffer pdf viewer, based on MuPDF")
    (description "A small framebuffer pdf viewer, based on MuPDF.  It is packaged from the Arch User Repository.")
    (license license:isc)))

;;; -- feishin (#11722) --

(define-public feishin
  (package
    (name "feishin")
    (version "1.11.0")
    (source (origin
              (method git-fetch)
              (uri (git-reference
                    (url "https://github.com/jeffvli/feishin.git")
                    (commit (string-append "v" version))))
              (file-name (git-file-name name version))
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system gnu-build-system)
    (arguments (list #:tests? #f))
    (home-page "https://github.com/jeffvli/feishin")
    (synopsis "a modern self-hosted music player")
    (description "A modern self-hosted music player.  It is packaged from the Arch User Repository.")
    (license license:gpl3)))

;;; -- file_clipper (#4380) --

(define-public file-clipper
  (package
    (name "file-clipper")
    (version "0.1.3")
    (source (origin
              (method git-fetch)
              (uri (git-reference
                    (url "https://github.com/ruiiiijiiiiang/file_clipper.git")
                    (commit (string-append "v" version))))
              (file-name (git-file-name name version))
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system cargo-build-system)
    (arguments (list #:tests? #f))
    (home-page "https://github.com/ruiiiijiiiiang/file_clipper")
    (synopsis "command line utility for copying/moving files")
    (description "Command line utility for copying/moving files.  It is packaged from the Arch User Repository.")
    (license license:expat)))

;;; -- firefly-iii (#12907) --

(define-public firefly-iii
  (package
    (name "firefly-iii")
    (version "6.5.9")
    (source (origin
              (method git-fetch)
              (uri (git-reference
                    (url "https://github.com/firefly-iii/firefly-iii.git")
                    (commit (string-append "v" version))))
              (file-name (git-file-name name version))
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system gnu-build-system)
    (arguments (list #:tests? #f))
    (home-page "https://github.com/firefly-iii/firefly-iii")
    (synopsis "pHP personal finances manager")
    (description "PHP personal finances manager.  It is packaged from the Arch User Repository.")
    (license license:agpl3)))

;;; -- flightgear-data (#11186) --

(define-public flightgear-data
  (package
    (name "flightgear-data")
    (version "2024.1.4")
    (source (origin
              (method git-fetch)
              (uri (git-reference
                    (url "https://gitlab.com/flightgear/fgdata.git")
                    (commit (string-append "v" version))))
              (file-name (git-file-name name version))
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system gnu-build-system)
    (arguments (list #:tests? #f))
    (home-page "https://gitlab.com/flightgear/fgdata")
    (synopsis "the FlightGear base package contains the necessary data files to run Flig")
    (description "The FlightGear base package contains the necessary data files to run FlightGear.  It is packaged from the Arch User Repository.")
    (license license:gpl2+)))

;;; -- fsel (#1145) --

(define-public fsel
  (package
    (name "fsel")
    (version "3.3.1")
    (source (origin
              (method git-fetch)
              (uri (git-reference
                    (url "https://github.com/Mjoyufull/fsel.git")
                    (commit (string-append "v" version))))
              (file-name (git-file-name name version))
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system cargo-build-system)
    (arguments (list #:tests? #f))
    (home-page "https://github.com/Mjoyufull/fsel")
    (synopsis "fast TUI app launcher and fuzzy finder for GNU/Linux and *BSD")
    (description "Fast TUI app launcher and fuzzy finder for GNU/Linux and *BSD.  It is packaged from the Arch User Repository.")
    (license license:bsd-2)))

;;; -- ftb-app-bin (#6808) --

(define-public ftb-app-bin
  (package
    (name "ftb-app-bin")
    (version "1.29.5")
    (source (origin
              (method url-fetch)
              (uri "https://feed-the-beast.com/ftb-app")
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system copy-build-system)
    (arguments (list #:install-plan
                     #~'((".", "share/" #:include-regexp (".*")))))
    (home-page "https://feed-the-beast.com/ftb-app")
    (synopsis "a new Modpack launcher for FTB and Curse modpacks")
    (description "A new Modpack launcher for FTB and Curse modpacks.  It is packaged from the Arch User Repository.")
    (license license:lgpl2.1)))

;;; -- gem2arch (#2011) --

(define-public gem2arch
  (package
    (name "gem2arch")
    (version "0.11")
    (source (origin
              (method git-fetch)
              (uri (git-reference
                    (url "https://github.com/anatol/gem2arch.git")
                    (commit (string-append "v" version))))
              (file-name (git-file-name name version))
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system gnu-build-system)
    (arguments (list #:tests? #f))
    (home-page "https://github.com/anatol/gem2arch")
    (synopsis "create PKGBUILD from Ruby Gem Package")
    (description "Create PKGBUILD from Ruby Gem Package.  It is packaged from the Arch User Repository.")
    (license license:gpl3+)))

;;; -- gemini-cli-git (#1617) --

(define-public gemini-cli-git
  (package
    (name "gemini-cli-git")
    (version "r3249.gc0b766ad7")
    (source (origin
              (method git-fetch)
              (uri (git-reference
                    (url "https://github.com/google-gemini/gemini-cli.git")
                    (commit (string-append "v" version))))
              (file-name (git-file-name name version))
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system node-build-system)
    (arguments (list #:tests? #f))
    (home-page "https://github.com/google-gemini/gemini-cli")
    (synopsis "an open-source AI agent that brings the power of Gemini directly into you")
    (description "An open-source AI agent that brings the power of Gemini directly into your terminal (git version).  It is packaged from the Arch User Repository.")
    (license license:asl2.0)))

;;; -- ginkgocadx-bin (#10707) --

(define-public ginkgocadx-bin
  (package
    (name "ginkgocadx-bin")
    (version "3.7.1.1573.46")
    (source (origin
              (method url-fetch)
              (uri "http://ginkgo-cadx.com/")
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system copy-build-system)
    (arguments (list #:install-plan
                     #~'((".", "share/" #:include-regexp (".*")))))
    (home-page "http://ginkgo-cadx.com/")
    (synopsis "complete DICOM viewer solution")
    (description "Complete DICOM viewer solution.  It is packaged from the Arch User Repository.")
    (license license:lgpl3+)))

;;; -- gitignore-downloader (#7383) --

(define-public gitignore-downloader
  (package
    (name "gitignore-downloader")
    (version "1.0.0")
    (source (origin
              (method git-fetch)
              (uri (git-reference
                    (url "https://github.com/cesarferreira/gitignore-downloader.git")
                    (commit (string-append "v" version))))
              (file-name (git-file-name name version))
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system cargo-build-system)
    (arguments (list #:tests? #f))
    (home-page "https://github.com/cesarferreira/gitignore-downloader")
    (synopsis "fetch and compose GitHub .gitignore templates from the terminal")
    (description "Fetch and compose GitHub .gitignore templates from the terminal.  It is packaged from the Arch User Repository.")
    (license license:expat)))

;;; -- gitversion-bin (#2974) --

(define-public gitversion-bin
  (package
    (name "gitversion-bin")
    (version "6.7.0")
    (source (origin
              (method url-fetch)
              (uri "https://github.com/GitTools/GitVersion/releases/download/v6.7.0/gitversion-6.7.0-linux-x86_64.tar.gz")
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system copy-build-system)
    (arguments (list #:install-plan
                     #~'((".", "share/" #:include-regexp (".*")))))
    (home-page "https://github.com/GitTools/GitVersion")
    (synopsis "from git log to SemVer in no time")
    (description "From git log to SemVer in no time.  It is packaged from the Arch User Repository.")
    (license license:expat)))

;;; -- gnatdoc (#7584) --

(define-public gnatdoc
  (package
    (name "gnatdoc")
    (version "26.0w")
    (source (origin
              (method git-fetch)
              (uri (git-reference
                    (url "https://github.com/AdaCore/gnatdoc.git")
                    (commit (string-append "v" version))))
              (file-name (git-file-name name version))
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system gnu-build-system)
    (arguments (list #:tests? #f))
    (home-page "https://github.com/AdaCore/gnatdoc")
    (synopsis "gNAT documentation generation tool")
    (description "GNAT documentation generation tool.  It is packaged from the Arch User Repository.")
    (license license:gpl3+)))

;;; -- go-grip (#1148) --

(define-public go-grip
  (package
    (name "go-grip")
    (version "0.9.0")
    (source (origin
              (method git-fetch)
              (uri (git-reference
                    (url "https://github.com/chrishrb/go-grip.git")
                    (commit (string-append "v" version))))
              (file-name (git-file-name name version))
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system go-build-system)
    (arguments (list #:tests? #f))
    (home-page "https://github.com/chrishrb/go-grip")
    (synopsis "preview Markdown files locally before committing them")
    (description "Preview Markdown files locally before committing them.  It is packaged from the Arch User Repository.")
    (license license:expat)))

;;; -- go-grip-git (#1147) --

(define-public go-grip-git
  (package
    (name "go-grip-git")
    (version "v0.5.6.r0.gac5f2a7")
    (source (origin
              (method git-fetch)
              (uri (git-reference
                    (url "https://github.com/chrishrb/go-grip.git")
                    (commit (string-append "v" version))))
              (file-name (git-file-name name version))
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system go-build-system)
    (arguments (list #:tests? #f))
    (home-page "https://github.com/chrishrb/go-grip")
    (synopsis "lightweight, Go-based tool designed to render Markdown files locally, rep")
    (description "Lightweight, Go-based tool designed to render Markdown files locally, replicating GitHub's style.  It is packaged from the Arch User Repository.")
    (license license:expat)))

;;; -- gopac-git (#4653) --

(define-public gopac-git
  (package
    (name "gopac-git")
    (version "1.2.1")
    (source (origin
              (method git-fetch)
              (uri (git-reference
                    (url "https://github.com/the-daonm/gopac.git")
                    (commit (string-append "v" version))))
              (file-name (git-file-name name version))
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system go-build-system)
    (arguments (list #:tests? #f))
    (home-page "https://github.com/the-daonm/gopac")
    (synopsis "a warm Gruvbox TUI for pacman and AUR (Git)")
    (description "A warm Gruvbox TUI for pacman and AUR (Git).  It is packaged from the Arch User Repository.")
    (license license:expat)))

;;; -- graphite-cli (#6799) --

(define-public graphite-cli
  (package
    (name "graphite-cli")
    (version "1.7.13")
    (source (origin
              (method url-fetch)
              (uri "https://graphite.dev/")
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system node-build-system)
    (arguments (list #:tests? #f))
    (home-page "https://graphite.dev/")
    (synopsis "graphite helps you create smaller pull requests, stay unblocked, and ship")
    (description "Graphite helps you create smaller pull requests, stay unblocked, and ship faster.  It is packaged from the Arch User Repository.")
    (license license:gpl3+)))

;;; -- hibiscus (#7661) --

(define-public hibiscus
  (package
    (name "hibiscus")
    (version "2.12.2")
    (source (origin
              (method url-fetch)
              (uri "https://www.willuhn.de/projects/hibiscus/")
              (sha256
               (base32 "0000000000000000000000000000000000000000000000000000"))))
    (build-system gnu-build-system)
    (arguments (list #:tests? #f))
    (home-page "https://www.willuhn.de/projects/hibiscus/")
    (synopsis "hBCI banking plugin for jameica")
    (description "HBCI banking plugin for jameica.  It is packaged from the Arch User Repository.")
    (license license:gpl2)))
