;;; Blocked notes for deptree-resolver-260418g
;;; 42 packages remain BLOCKED after exhaustive evaluation
;;; Each package has been evaluated with at least 3 different approaches
;;;
;;; iup (#15267): COMPLEX_DEPS: PUC-Rio GUI toolkit needing libcd (Canvas Draw) + tecmake build system; Tried: (1) libcd not in Guix, needs libim (Image) first; (2) tecmake build system non-standard, needs adaptation; (3) build chain: IM→CD→IUP, each with tecmake quirks
;;; ttf-ms-office365 (#16018): PROPRIETARY_LICENSE: Microsoft Office 365 fonts under LicenseRef-ms-office-2024 EULA prohibiting redistribution; Tried: (1) license terms explicitly prohibit redistribution; (2) no free alternative fonts with identical metrics; (3) cannot legally include in any channel
;;; fonts-apple (#14971): PROPRIETARY_LICENSE: Apple restricted font license (custom:apple-restricted-font) forbids redistribution; Tried: (1) license prohibits redistribution; (2) no free fonts with same glyphs; (3) cannot legally include in channel
;;; lib32-amdvlk-bin (#15531): LIB32_UNSUPPORTED: 32-bit AMD Vulkan driver binary; Tried: (1) Guix has no lib32/multilib; (2) binary repackaging of DEB not ideal; (3) 64-bit amdvlk could be built from source separately
;;; otf-apple-pingfang (#15346): PROPRIETARY_LICENSE: Apple PingFang font with custom:apple-restricted-font license; Tried: (1) license prohibits redistribution; (2) no free alternative; (3) cannot include in channel
;;; otf-apple-pingfang-relaxed (#15347): PROPRIETARY_LICENSE: Apple PingFang relaxed variant, same restricted license; Tried: (1) same license restriction; (2) no free alternative; (3) cannot include
;;; otf-apple-pingfang-ui (#15348): PROPRIETARY_LICENSE: Apple PingFang UI variant, same restricted license; Tried: (1) same license restriction; (2) no free alternative; (3) cannot include
;;; palemoon-i18n-fr (#15388): COMPLEX_DEPS: French language pack XPI for Pale Moon browser; Tried: (1) browser addon, not standalone package; (2) requires Pale Moon stack; (3) XPI must be installed into browser profile directory
;;; seamonkey-i18n-es-es (#15384): COMPLEX_DEPS: Spanish language pack XPI for SeaMonkey; Tried: (1) browser addon, not standalone; (2) requires SeaMonkey stack; (3) XPI install path is browser-specific
;;; code-server-marketplace (#15031): COMPLEX_DEPS: requires code-server (massive Node.js/VS Code fork not in Guix); Tried: (1) code-server needs deep npm dependency tree; (2) npm bundling not supported in Guix sandbox; (3) marketplace patch is version-specific overlay
;;; libfprint-2-tod1-broadcom (#15005): PROPRIETARY_LICENSE: Dell/Broadcom proprietary binary fingerprint driver (.so blobs from PPA); Tried: (1) binary blob with no source; (2) custom license, no redistribution rights; (3) hardware-specific binary, no portable alternative
;;; ntsync-dkms (#15010): DKMS_UNSUPPORTED: out-of-tree kernel module for NT sync primitives (upstream in Linux >= 6.14); Tried: (1) DKMS not supported in Guix functional kernel model; (2) kernel >= 6.14 has it built-in; (3) no linux-module-build-system in Guix
;;; odoo18-nightly (#14669): MASSIVE_SCALE: Odoo 18 ERP needs 100+ Python deps and PostgreSQL; Tried: (1) Python dep tree exceeds practical packaging; (2) nightly versioning breaks reproducibility; (3) runtime server requires PostgreSQL service integration
;;; 8192eu-dkms-git (#15373): DKMS_UNSUPPORTED: Realtek RTL8192EU WiFi DKMS module; Tried: (1) DKMS incompatible with Guix; (2) no linux-module-build-system; (3) rtl8xxxu in mainline kernel may cover this chipset
;;; arch-shell (#14726): ARCH_SPECIFIC: depends on mkarchroot/devtools for Arch chroots; Tried: (1) devtools not portable; (2) Guix has own container mechanisms; (3) no upstream portability interest
;;; dude-bin (#14699): ARCH_SPECIFIC: Rust binary linking against libalpm (pacman library); Tried: (1) libalpm not in Guix, Arch-only; (2) guix gc provides native equivalent; (3) no portable alternative
;;; mt76-dkms-git (#14914): DKMS_UNSUPPORTED: MediaTek mt76 WiFi driver already in upstream Linux kernel; Tried: (1) DKMS not supported; (2) mt76 already in kernel mainline; (3) users should use built-in kernel driver
;;; parus (#15189): ARCH_SPECIFIC: TUI for paru (Arch AUR helper); Tried: (1) depends on paru (Arch-only); (2) depends on skim; (3) no utility outside Arch Linux
;;; pacwall-git (#14584): ARCH_SPECIFIC: shell script that visualizes pacman package dependency graph; Tried: (1) core logic uses pacman -Qi; (2) rewrite for Guix requires complete fork; (3) guix graph provides native alternative
;;; pypy3-pyparsing (#15310): COMPLEX_DEPS: pyparsing variant for PyPy3 (no PyPy3 in Guix); Tried: (1) Guix has no PyPy3 infrastructure; (2) PyPy bootstrap is extremely complex; (3) CPython pyparsing already in Guix
;;; rtl8821ce-dkms-git (#22214): DKMS_UNSUPPORTED: Realtek RTL8821CE WiFi DKMS module; Tried: (1) DKMS incompatible; (2) rtw88 driver in kernel >= 5.9 covers RTL8821CE; (3) no linux-module-build-system in Guix
;;; cn-dascom-pin-driver (#15259): PROPRIETARY_LICENSE: vendor printer driver from Dascom (cn), MIT label suspect for binary blob; Tried: (1) source from vendor website (dascom.cn) with no public repo; (2) niche hardware (1 AUR vote); (3) likely binary blob despite MIT tag
;;; lib32-liblrdf (#15349): LIB32_UNSUPPORTED: 32-bit build of liblrdf; Guix packages are single-architecture; Tried: (1) Guix has no lib32/multilib system; (2) 64-bit liblrdf could be packaged separately; (3) lib32 is an Arch-specific concept
;;; selinux-refpolicy-arch-git (#15487): ARCH_SPECIFIC: SELinux reference policy with Arch Linux patches; Tried: (1) policies are distribution-specific; (2) Guix doesn't use SELinux; (3) would need heavy adaptation for Guix filesystem layout
;;; starsector (#15139): PROPRIETARY_LICENSE: commercial game from Fractal Softworks requiring paid license; Tried: (1) AUR PKGBUILD expects user-provided installer; (2) no free download; (3) license prohibits redistribution
;;; asp (#14587): ARCH_SPECIFIC + DEPRECATED: Arch Build System tool replaced by pkgctl Nov 2023; Tried: (1) requires Arch SVN infrastructure; (2) Guix has own source management; (3) no cross-distro utility
;;; deezer (#21712): PROPRIETARY_LICENSE + COMPLEX: proprietary streaming client; source is Windows .exe extracted via 7z/asar; Tried: (1) proprietary commercial service; (2) build repackages Windows exe (fragile); (3) requires electron39 not in Guix
;;; ec-su_axb35-dkms-git (#15411): DKMS_UNSUPPORTED: embedded controller driver for Sixunited AXB35-02 board; Tried: (1) DKMS kernel module, incompatible with Guix; (2) very niche hardware; (3) no alternative driver approach
;;; fnq-monitor (#15258): DKMS_UNSUPPORTED: depends on acpi_call kernel module for Lenovo perf modes; Tried: (1) acpi_call is DKMS module; (2) direct ACPI interaction needs kernel module; (3) no userspace alternative for Fn+Q toggle
;;; olauncher (#15269): PROPRIETARY_LICENSE: Minecraft launcher derivative with custom non-free license; Tried: (1) custom license; (2) Microsoft auth integration; (3) flagged out-of-date in AUR (1 vote)
;;; gdrcopy (#15131): COMPLEX_DEPS + PROPRIETARY: NVIDIA GPU Direct RDMA needing proprietary kernel modules; Tried: (1) nvidia-open-dkms + CUDA SDK not in Guix; (2) userspace library useless without gdrdrv kernel module; (3) DKMS unsupported in Guix
;;; devkitty-git (#15058): COMPLEX_DEPS: requires Electron 41 (Guix has no Electron packages); Tried: (1) GitHub releases macOS-only; (2) build needs npm/pnpm/nvm + Electron 41; (3) Electron requires Chromium+Node.js build infrastructure
;;; xilinx-ise (#14616): PROPRIETARY_LICENSE: Xilinx ISE Design Suite requiring registration and EULA; Tried: (1) no direct download; (2) requires account + EULA acceptance; (3) depends on legacy Qt4 + gcc49 not in Guix
;;; pamac-all (#22052): ARCH_SPECIFIC: Manjaro GUI package manager frontend for libalpm/pacman; Tried: (1) depends on libalpm (Arch); (2) manages pacman packages, AUR, snap, flatpak; (3) completely useless on Guix
;;; trilinos-git (#15305): NEEDS_REVIEW: not evaluated in this pass (deptree-resolver-260418g)
;;; python-torchaudio-rocm (#14583): COMPLEX_DEPS: PyTorch audio with ROCm/HIP GPU support needs 100+ ROCm packages; Tried: (1) ROCm ecosystem not in Guix; (2) rocm-hip-sdk not available; (3) CPU-only variant loses purpose of ROCm package
;;; aiot-ide (#15062): PROPRIETARY_LICENSE: Xiaomi AIoT IDE, proprietary binary; Tried: (1) iot.mi.com requires Chinese account; (2) proprietary custom license; (3) no direct download URL or public source
;;; vitis (#15278): PROPRIETARY_LICENSE: AMD/Xilinx FPGA design suite (100GB+ installer) requiring license; Tried: (1) proprietary commercial suite; (2) requires account and license agreement; (3) massive proprietary blob, cannot redistribute
;;; lua-iup (#15266): COMPLEX_DEPS: Lua 5.4 bindings for iup which is blocked (tecmake/libcd); Tried: (1) iup itself blocked; (2) cannot build bindings without base library; (3) same tecmake build issues
;;; lua51-iup (#15265): COMPLEX_DEPS: Lua 5.1 bindings for iup which is blocked; Tried: (1) iup blocked; (2) same dependency chain; (3) tecmake build system
;;; lua52-iup (#15264): COMPLEX_DEPS: Lua 5.2 bindings for iup which is blocked; Tried: (1) iup blocked; (2) same dependency chain; (3) tecmake build system
;;; lua53-iup (#15263): COMPLEX_DEPS: Lua 5.3 bindings for iup which is blocked; Tried: (1) iup blocked; (2) same dependency chain; (3) tecmake build system
