;;; GNU Guix --- Functional package management for GNU
;;; Copyright (C) 2026 Gaurix Contributors
;;;
;;; Dependency-tree resolver pass --- deptree-resolver-260428j
;;; 100 BLOCKED evaluated, 3 resolved to DONE, 2 new dependency packages.
;;; 5 new recipes total:
;;;   python-libnmap (new dep for scans2any-git)
;;;   python-partial-json-parser (new dep for scans2any-git)
;;;   scans2any-git → DONE
;;;   oclint → DONE
;;;   deadbeef-git → DONE
;;; 97 remain BLOCKED (intractable categories confirmed).
;;;
;;; Key changes since last pass:
;;; - libdispatch@5.9.2 in Guix includes libBlocksRuntime.so → unblocks deadbeef-git
;;; - All LLVM/Clang deps for oclint confirmed available (LLVM 21.1.8)
;;; - python-libnmap + python-partial-json-parser packaged → unblocks scans2any-git
;;;
;;; Verification: upstream Guix checked for all 100 (none found).
;;; Key deps: rust=1.85.1, electron=36.8.1, dotnet=8.0, node=22.14.0,
;;;   llvm=21.1.8, clang=21.1.8, libdispatch=5.9.2, mupdf=1.26.8.
;;; Crystal, .NET 9.0, Rust 1.89+, Zig, wayfire still unavailable in Guix.
;;;
;;; See deptree-resolver-260428j-blocked-notes.scm for detailed evaluation.
;;;
;;; Generated: 2026-04-28

(define-module (gaurix packages deptree-resolver-260428j)
  #:use-module (guix packages)
  #:use-module (guix download)
  #:use-module (guix git-download)
  #:use-module (guix gexp)
  #:use-module (guix utils)
  #:use-module (guix build-system cmake)
  #:use-module (guix build-system gnu)
  #:use-module (guix build-system python)
  #:use-module (guix build-system pyproject)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (gnu packages)
  #:use-module (gnu packages audio)
  #:use-module (gnu packages autotools)
  #:use-module (gnu packages c)
  #:use-module (gnu packages cdrom)
  #:use-module (gnu packages check)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages curl)
  #:use-module (gnu packages freedesktop)
  #:use-module (gnu packages gettext)
  #:use-module (gnu packages glib)
  #:use-module (gnu packages gnome)
  #:use-module (gnu packages gtk)
  #:use-module (gnu packages icu4c)
  #:use-module (gnu packages image)
  #:use-module (gnu packages libffi)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages llvm)
  #:use-module (gnu packages mp3)
  #:use-module (gnu packages ninja)
  #:use-module (gnu packages pkg-config)
  #:use-module (gnu packages pulseaudio)
  #:use-module (gnu packages python)
  #:use-module (gnu packages python-build)
  #:use-module (gnu packages python-check)
  #:use-module (gnu packages python-science)
  #:use-module (gnu packages python-web)
  #:use-module (gnu packages python-xyz)
  #:use-module (gnu packages terminals)
  #:use-module (gnu packages text-editors)
  #:use-module (gnu packages video)
  #:use-module (gnu packages web)
  #:use-module (gnu packages xiph)
  #:use-module (gnu packages xml)
  #:use-module (gnu packages xorg)
  #:export (python-libnmap
            python-partial-json-parser
            scans2any-git
            oclint
            deadbeef-git))

;;; ========================================================================
;;; NEW DEPENDENCY: python-libnmap
;;; ========================================================================

(define-public python-libnmap
  (package
    (name "python-libnmap")
    (version "0.7.3")
    (source
     (origin
       (method url-fetch)
       (uri (pypi-uri "python-libnmap" version))
       (sha256
        (base32 "1h1nb5a7j9zkw2wqmpb1136kg5mfqb2d8a0c74vsps9fdhjjjdnh"))))
    (build-system pyproject-build-system)
    (arguments (list #:tests? #f))  ;; tests require nmap binary
    (native-inputs (list python-setuptools))
    (home-page "https://libnmap.readthedocs.io/")
    (synopsis "Python library to parse nmap XML results")
    (description
     "Python NMAP library enabling you to start async nmap tasks, parse
and compare/diff scan results.  It provides a Pythonic interface to
nmap's XML output format.")
    (license license:asl2.0)))

;;; ========================================================================
;;; NEW DEPENDENCY: python-partial-json-parser
;;; ========================================================================

(define-public python-partial-json-parser
  (package
    (name "python-partial-json-parser")
    (version "0.2.1.1.post7")
    (source
     (origin
       (method url-fetch)
       (uri (pypi-uri "partial_json_parser" version))
       (sha256
        (base32 "08m9r4r936bnncyy4v2c9y4bb3027wrd45zw5nd77dmwlqdhwnc6"))))
    (build-system pyproject-build-system)
    (arguments (list #:tests? #f))
    (propagated-inputs (list python-rich))
    (native-inputs (list python-pdm-backend))
    (home-page "https://github.com/nobu-g/partial-json-parser")
    (synopsis "Parse partial JSON generated by LLM")
    (description
     "Parse partial JSON generated by LLM.  Useful for streaming
JSON responses from large language models where the complete JSON
may not yet be available.")
    (license license:expat)))

;;; ========================================================================
;;; RESOLVED: scans2any-git
;;; ========================================================================

(define-public scans2any-git
  (package
    (name "scans2any-git")
    (version "1.0.0.post0")
    (source
     (origin
       (method git-fetch)
       (uri (git-reference
             (url "https://github.com/softScheck/scans2any")
             (commit "bcd2b3b")))
       (file-name (git-file-name name version))
       (sha256
        (base32 "05hq66bs74kwwz4anh2y24ls36rz83f3g83dll69ny773blrb52v"))))
    (build-system pyproject-build-system)
    (arguments (list #:tests? #f))
    (propagated-inputs
     (list python-jinja2
           python-libnmap
           python-pandas
           python-partial-json-parser
           python-sortedcontainers
           python-tabulate
           python-rich
           python-pyyaml
           python-defusedxml
           python-pydantic))
    (native-inputs
     (list python-setuptools
           python-wheel))
    (home-page "https://github.com/softScheck/scans2any")
    (synopsis "Convert and merge infrastructure scans to various formats")
    (description
     "Scans2any converts and merges infrastructure scan results to Typst,
Markdown, HTML, and other formats.  It processes output from common
security scanning tools and produces unified reports.")
    (license license:agpl3+)))

;;; ========================================================================
;;; RESOLVED: oclint
;;; ========================================================================

(define-public oclint
  (package
    (name "oclint")
    (version "26.02")
    (source
     (origin
       (method url-fetch)
       (uri (string-append
             "https://github.com/oclint/oclint/archive/refs/tags/v"
             version ".tar.gz"))
       (sha256
        (base32 "1vann8hycm125fsggagfqyk49ldq996npql1rvk3i7sdv4hf1ldb"))))
    (build-system cmake-build-system)
    (arguments
     (list
      #:tests? #f
      #:configure-flags
      #~(list (string-append "-DCMAKE_PREFIX_PATH="
                             #$(this-package-input "llvm"))
              (string-append "-DCLANG_PREFIX="
                             #$(this-package-input "clang")))))
    (inputs
     (list clang
           llvm
           zlib
           xz
           libffi
           libedit
           libxml2
           icu4c))
    (native-inputs
     (list cmake
           ninja
           python))
    (home-page "https://oclint.org/")
    (synopsis "Static source code analysis tool for C, C++ and Objective-C")
    (description
     "OCLint is a static code analysis tool for improving quality and
reducing defects by inspecting C, C++ and Objective-C code.  It looks
for potential problems such as possible bugs, unused code, complicated
code, redundant code, code smells, and bad practices.")
    (license license:bsd-3)))

;;; ========================================================================
;;; RESOLVED: deadbeef-git
;;; ========================================================================

(define-public deadbeef-git
  (package
    (name "deadbeef-git")
    (version "1.9.6.r12073")
    (source
     (origin
       (method git-fetch)
       (uri (git-reference
             (url "https://github.com/DeaDBeeF-Player/deadbeef")
             (commit "40c0f3a")))
       (file-name (git-file-name name version))
       (sha256
        (base32 "05dw2532jvl95x8nxf8ffbk4n5c2larlwzxl782902ib30aln7vb"))))
    (build-system gnu-build-system)
    (arguments
     (list
      #:tests? #f
      #:phases
      #~(modify-phases %standard-phases
          (add-before 'configure 'set-clang-env
            (lambda _
              (setenv "CC" "clang")
              (setenv "CXX" "clang++"))))))
    (inputs
     (list alsa-lib
           curl
           faad2
           ffmpeg
           flac
           glib
           gtk+
           gtk+-2
           imlib2
           jansson
           libcddb
           libcdio
           libdispatch
           libmad
           libsamplerate
           libvorbis
           libx11
           libzip
           pipewire
           pulseaudio
           wavpack))
    (native-inputs
     (list autoconf
           automake
           clang
           gettext-minimal
           intltool
           libtool
           pkg-config
           yasm))
    (home-page "https://deadbeef.sourceforge.io/")
    (synopsis "GTK+ audio player for GNU/Linux")
    (description
     "DeaDBeeF is a modular audio player for GNU/Linux and other
UNIX-like systems.  It supports many audio formats including MP3, Ogg
Vorbis, FLAC, APE, WavPack, and more through its plugin system.
Features include gapless playback, cue sheet support, and multiple
output backends.")
    (license (list license:gpl2+
                   license:lgpl2.1+
                   license:zlib))))
