;;; Blocked notes for deptree-resolver-260417ad
;;; 42 packages remain BLOCKED after exhaustive evaluation
;;;
;;; raidrivecli (#14202): MISSING_SOURCE + PROPRIETARY: not in AUR cache; proprietary cloud storage CLI with no public source or binary; Tried: (1) AUR search -- no PKGBUILD; (2) web search -- no public download; (3) vendor site requires paid license
;;; redact-bin (#15032): PROPRIETARY_LICENSE: proprietary Electron app with no source and commercial license; Tried: (1) no source available; (2) custom commercial license; (3) binary analysis shows no redistribution clause
;;; ttf-ms-office365 (#16018): PROPRIETARY_LICENSE: Microsoft Office fonts prohibit redistribution; Tried: (1) LicenseRef-ms-office-2024; (2) requires MS Office license; (3) cannot include in channel
;;; fonts-apple (#14971): PROPRIETARY_LICENSE: Apple restricted font license forbids redistribution; Tried: (1) license terms prohibit redistribution; (2) no free alternative with same glyphs; (3) cannot legally include in channel
;;; gizmosql-bin (#15122): SOURCE_UNAVAILABLE: commercial product with no public download; Tried: (1) gizmodata.com -- commercial; (2) no GitHub repo; (3) AUR PKGBUILD uses private download source
;;; mdatp-bin (#15203): PROPRIETARY_LICENSE: Microsoft Defender ATP; Tried: (1) MS repos require agreement; (2) custom commercial license; (3) systemd tight coupling
;;; otf-apple-pingfang (#15346): PROPRIETARY_LICENSE: Apple PingFang font with restricted redistribution; Tried: (1) apple-restricted-font license; (2) no free redistribution; (3) cannot include in channel
;;; otf-apple-pingfang-relaxed (#15347): PROPRIETARY_LICENSE: Apple PingFang variant with restricted license; Tried: (1) same apple-restricted-font; (2) no free redistribution; (3) cannot include
;;; otf-apple-pingfang-ui (#15348): PROPRIETARY_LICENSE: Apple PingFang UI variant with restricted license; Tried: (1) same apple-restricted-font; (2) no free redistribution; (3) cannot include
;;; chatgqt (#14575): SOURCE_UNAVAILABLE: no URL in AUR metadata; no upstream repository found; Tried: (1) AUR metadata has no URL field; (2) searched GitHub/GitLab -- no repo; (3) package appears to be inline PKGBUILD with no external source
;;; code-server-marketplace (#15031): COMPLEX_DEPS: requires code-server (complex Node.js app not in Guix); Tried: (1) depends on code-server; (2) code-server itself needs deep npm tree; (3) marketplace patch is version-specific
;;; libfprint-2-tod1-broadcom (#15005): PROPRIETARY_LICENSE: Dell/Broadcom binary fingerprint driver blobs; Tried: (1) PPA has .so blobs -- proprietary; (2) no source code available; (3) restricted license
;;; ntsync-dkms (#15010): DKMS_UNSUPPORTED: ntsync upstream in Linux >= 6.14; Tried: (1) DKMS not supported in Guix; (2) users with kernel >= 6.14 have it built-in; (3) out-of-tree module packaging impossible without DKMS
;;; odoo18-nightly (#14669): MASSIVE_SCALE: Odoo 18 ERP needs 500+ Python deps and PostgreSQL; Tried: (1) Python dep tree (500+) exceeds practical packaging; (2) nightly versioning breaks reproducibility; (3) PostgreSQL service integration requires system design
;;; plexamp-bin (#15521): PROPRIETARY_LICENSE + COMPLEX: Plex proprietary Electron app; Tried: (1) custom license prohibits redistribution; (2) requires electron38 not in Guix; (3) AppImage extraction still needs Electron runtime
;;; arch-shell (#14726): ARCH_SPECIFIC: depends on mkarchroot/devtools for Arch chroots; Tried: (1) devtools not portable; (2) Guix has own container/profile mechanisms; (3) no upstream portability interest
;;; dude-bin (#14699): ARCH_SPECIFIC: Rust binary linking against libalpm (pacman library); Tried: (1) libalpm not in Guix and Arch-only; (2) guix gc --delete-generations provides native equivalent; (3) no portable alternative exists
;;; mt76-dkms-git (#14914): DKMS_UNSUPPORTED: out-of-tree DKMS kernel module; mt76 driver already upstream in Linux; Tried: (1) DKMS not supported in Guix; (2) mt76 already in kernel; (3) users should use kernel built-in mt76
;;; parus (#15189): ARCH_SPECIFIC: TUI for paru (Arch AUR helper); Tried: (1) depends on paru (Arch-only); (2) depends on skim; (3) no utility outside Arch Linux
;;; verapdf (#15191): COMPLEX_PACKAGING: Java/Maven app with no GitHub release assets; Tried: (1) no release binaries on GitHub; (2) Maven Central distribution requires maven-build-system; (3) maven-build-system in Guix poorly maintained; installer requires JRE wrapper
;;; cryptpad (#15184): NPM_COMPLEX: Node.js web app with 100+ npm dependencies; Tried: (1) node-build-system requires each dep individually; (2) npm bundling not supported in sandbox; (3) requires runtime Node.js server with persistent state
;;; pacwall-git (#14584): ARCH_SPECIFIC: shell script queries pacman database exclusively; Tried: (1) core logic uses pacman -Qi; (2) rewrite for Guix requires complete fork; (3) guix graph provides native alternative
;;; iriunwebcam-bin (#15158): PROPRIETARY_LICENSE + KERNEL_MODULE: proprietary binary needing v4l2loopback DKMS; Tried: (1) proprietary binary with no source; (2) v4l2loopback needs kernel module build; (3) DKMS unsupported in Guix
;;; starsector (#15139): PROPRIETARY_LICENSE: commercial game requiring paid license; Tried: (1) AUR PKGBUILD expects user-provided installer; (2) no free download; (3) license prohibits redistribution
;;; amsel_suite-bin (#15316): PROPRIETARY_LICENSE: TTRPG companion with commercial license; Tried: (1) custom:commercial; (2) proprietary binary; (3) redistribution prohibited
;;; asp (#14587): ARCH_SPECIFIC + DEPRECATED: Arch Build System tool replaced by pkgctl Nov 2023; Tried: (1) requires Arch SVN infrastructure; (2) Guix has own source management; (3) no cross-distro utility
;;; deemix-gui-appimage (#14759): LEGAL_ISSUES + SOURCE_UNAVAILABLE: Deezer music downloader archived by maintainers after legal action; Tried: (1) project taken down; (2) no stable source URL; (3) legal risk for redistribution
;;; python-jupyterlab-variableinspector (#15188): NPM_PYTHON_HYBRID: JupyterLab extension requires npm build + Python; Tried: (1) npm build needs network; (2) pre-built wheel needs JupyterLab extension directory structure; (3) JupyterLab extension ecosystem poorly supported in Guix
;;; gdrcopy (#15131): COMPLEX_DEPS: NVIDIA GPU Direct RDMA requiring proprietary kernel modules; Tried: (1) NVIDIA kernel modules not in Guix; (2) userspace library useless without gdrdrv; (3) HPC/CUDA workloads incompatible with Guix sandbox
;;; brother-mfc-j5720dw (#15008): PROPRIETARY_LICENSE + ARCH_SPECIFIC: Brother proprietary printer driver with i386 binary blobs; Tried: (1) contains i386 binaries; (2) requires lib32-glibc; (3) proprietary license
;;; devkitty-git (#15058): COMPLEX_DEPS: requires Electron 41 (not in Guix); Tried: (1) GitHub releases macOS-only; (2) build needs npm/pnpm/nvm + Electron 41; (3) no Linux binary published
;;; xilinx-ise (#14616): PROPRIETARY_LICENSE: registration-walled 6GB+ installer requiring Xilinx EULA; Tried: (1) no direct download URL; (2) requires account + EULA acceptance; (3) depends on legacy Qt4 + gcc49 not in Guix
;;; 115-browser-bin (#15178): PROPRIETARY_LICENSE: Chinese browser with commercial license; Tried: (1) 115.com requires Chinese region access; (2) LicenseRef-scancode-commercial-license; (3) binary depends on system Chromium libs
;;; python-gpustat (#15182): COMPLEX_DEPS: requires NVIDIA pynvml runtime not in Guix; Tried: (1) nvidia-ml-py not in Guix; (2) nvidia-utils not in Guix; (3) package useless without NVIDIA GPU driver at runtime
;;; magicq (#15200): PROPRIETARY_LICENSE: ChamSys proprietary lighting control; Tried: (1) free download but custom license; (2) redistribution terms unclear; (3) proprietary binary-only
;;; python-birdseye (#15207): COMPLEX_DEPS: Flask debugger needing 4+ missing Python deps; Tried: (1) python-flask-humanize not in Guix; (2) python-littleutils not in Guix; (3) python-cheap-repr not in Guix; chain packaging exceeds scope
;;; zzzfm-bin (#15221): COMPLEX_DEPS: GTK2 file manager needing zzzfm-common; Tried: (1) depends on zzzfm-common-bin (not in Guix); (2) GitLab has source but no binary releases; (3) would need to package zzzfm-common first, GTK2 app with deep deps
;;; python-torchaudio-rocm (#14583): COMPLEX_DEPS: PyTorch audio with ROCm/HIP GPU support requires massive dep chain; Tried: (1) ROCm ecosystem (100+ packages) not in Guix; (2) rocm-hip-sdk not available; (3) CPU-only variant loses purpose of ROCm package
;;; void-electron-latest-bin (#14576): COMPLEX_DEPS: Void editor (VS Code fork) needs Electron 34 not in Guix; Tried: (1) GitHub has no Linux binaries; (2) build from source needs Electron 34 (not in Guix); (3) system Electron version mismatch breaks app
;;; godot-double-mono (#14495): DOTNET_UNSUPPORTED: Godot double-precision with C#/Mono requires .NET SDK 8.0 not in Guix; Tried: (1) build from source needs dotnet-sdk-8.0 + nuget; (2) pre-built binary none published with double+mono for Linux; (3) strip Mono defeats package purpose vs godot-double
;;; aiot-ide (#15062): PROPRIETARY_LICENSE: Xiaomi proprietary IoT IDE with no public source; Tried: (1) iot.mi.com requires Chinese account; (2) proprietary custom license; (3) no direct download URL
;;; unofficial-homestuck-collection-bin (#15324): ELECTRON_MASSIVE: Electron app >2GB with bundled Chromium + multimedia; Tried: (1) AppImage extraction yields 2GB+ runtime; (2) no lightweight alternative; (3) asset size + Electron deps impractical
