(define-module (gaurix packages fluxer-bin)
  #:use-module (guix packages)
  #:use-module (guix download)
  #:use-module (guix gexp)
  #:use-module (guix build-system trivial)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages base))

(define-public fluxer-bin
  (package
    (name "fluxer-bin")
    (version "0.0.8")
    (source
     (origin
       (method url-fetch)
       (uri "https://api.fluxer.app/dl/desktop/stable/linux/x64/latest/tar_gz")
       ;; AUR fluxer-bin x86_64 hash
       (sha256 (base32 "0b8gc31lc91wv5xgrwkbxi7xprr4nc8w01jvv3z201w1ls7kkxmc"))))
    (build-system trivial-build-system)
    (native-inputs (list tar gzip))
    (arguments
     (list
      #:modules '((guix build utils)
                  (ice-9 ftw)
                  (srfi srfi-1))
      #:builder
      #~(begin
          (use-modules (guix build utils)
                       (ice-9 ftw)
                       (srfi srfi-1))
          (let* ((out (assoc-ref %outputs "out"))
                 (src (assoc-ref %build-inputs "source"))
                 (tar (search-input-file %build-inputs "/bin/tar"))
                 (gzip (search-input-file %build-inputs "/bin/gzip"))
                 (apps (string-append out "/share/applications"))
                 (icons (string-append out "/share/icons/hicolor/512x512/apps"))
                 (opt (string-append out "/opt/fluxer-bin"))
                 (bin (string-append out "/bin")))
            (invoke tar (string-append "--use-compress-program=" gzip) "-xf" src)
            (let* ((entries (scandir "." (lambda (n) (not (member n '("." ".."))))))
                   (dir (find (lambda (n)
                                (and (file-is-directory? n)
                                     (string-prefix? "fluxer-stable-" n)))
                              entries)))
              (unless dir
                (error "Could not locate extracted fluxer directory"))
              (mkdir-p opt)
              (copy-recursively dir opt)
              (mkdir-p bin)
              (symlink (string-append opt "/fluxer") (string-append bin "/fluxer"))
              (mkdir-p apps)
              (call-with-output-file (string-append apps "/fluxer.desktop")
                (lambda (p)
                  (display "[Desktop Entry]\nName=Fluxer\nComment=Fluxer Desktop App\nExec=fluxer\nIcon=fluxer\nTerminal=false\nType=Application\nCategories=Internet;\n" p)))
              (let ((icon-src (string-append opt "/resources/512x512.png")))
                (when (file-exists? icon-src)
                  (mkdir-p icons)
                  (copy-file icon-src (string-append icons "/fluxer.png"))))
              #t)))))
    (home-page "https://fluxer.app")
    (synopsis "Fluxer desktop application (binary)")
    (description "Binary package of Fluxer desktop app.")
    (license license:agpl3)))
