;;; Blocked notes for queue-20260323p100d queue drain (2026-03-23).
;;; 64 entries blocked with NEEDS_RECIPE_DESIGN or SOURCE_UNAVAILABLE after Guix availability probe.
(define-module (gaurix packages queue-20260323p100d-blocked-notes)
  #:export (queue-20260323p100d-blocked-notes))

(define queue-20260323p100d-blocked-notes
  (list
  ;; ── Binary/proprietary distribution ────────────────────────────────────
  '(djv NEEDS_RECIPE_DESIGN "No Guix djv; media player/review tool at https://djv.sourceforge.net/; C++ cmake + OpenGL + Qt; Next: pin release, fetch source tarball, draft cmake recipe")
  '(dol-bin NEEDS_RECIPE_DESIGN "No Guix dol; binary at https://github.com/nicowillis/dol/releases; needs binary wrapper or cargo recipe; Next: identify upstream language, fetch binary, compute hash")
  '(netlogo NEEDS_RECIPE_DESIGN "No Guix netlogo; agent-based modelling platform at https://ccl.northwestern.edu/netlogo/; Java application + data; needs openjdk wrapper recipe; Next: fetch installer, compute hash, draft java binary recipe")
  '(cctag NEEDS_RECIPE_DESIGN "No Guix cctag; CCTag computer vision library at https://github.com/alicevision/CCTag; C++ cmake + Boost + CUDA optional; Next: fetch source, draft cmake recipe")
  '(logiops-rs NEEDS_RECIPE_DESIGN "No Guix logiops-rs; Rust rewrite of logiops at unknown upstream; cargo recipe needed; Next: locate correct upstream repo, pin version, draft cargo recipe")
  '(meshroom NEEDS_RECIPE_DESIGN "No Guix meshroom; photogrammetry software at https://github.com/alicevision/Meshroom; C++/Python cmake + alicevision deps; complex build; Next: assess deps, draft cmake recipe or binary wrapper")
  '(kfr NEEDS_RECIPE_DESIGN "No Guix kfr; DSP library at https://github.com/kfrlib/kfr; C++ cmake header-only+optional; Next: fetch source, draft cmake recipe")
  '(recorder NEEDS_RECIPE_DESIGN "No Guix recorder; ambiguous upstream (multiple projects named recorder); Next: check AUR PKGBUILD to identify correct upstream repo and build system")
  '(nirinit-git NEEDS_RECIPE_DESIGN "No Guix nirinit; Niri Wayland compositor init helper git; source https://github.com/YaLTeR/niri or similar; Next: identify correct upstream, draft recipe")
  '(ledfx-cc-bin NEEDS_RECIPE_DESIGN "No Guix ledfx-cc; LED effects controller binary at https://github.com/YeonV/LedFx-Frontend; Electron binary; Next: fetch binary release, compute hash, draft binary wrapper recipe")
  '(go-hass-agent NEEDS_RECIPE_DESIGN "No Guix go-hass-agent; Home Assistant agent in Go at https://github.com/joshuar/go-hass-agent; needs go-build-system recipe; Next: pin version, fetch source, draft go recipe")
  '(electron12-bin NEEDS_RECIPE_DESIGN "No Guix electron12; electron 12.x EOL binary; needs binary wrapper with patchelf; electron12 is EOL; Next: assess if still needed, fetch binary, draft recipe")
  '(wayfarer-git NEEDS_RECIPE_DESIGN "No Guix wayfarer; Wayfarer Wayland hotkey daemon at https://github.com/nicowillis/wayfarer or similar; git; Next: identify correct upstream, assess build system, draft recipe")
  '(blinky NEEDS_RECIPE_DESIGN "No Guix blinky; ambiguous (possibly LED/notification manager); AUR votes=6; Next: check AUR PKGBUILD to confirm upstream URL and build system")
  '(alice-vision NEEDS_RECIPE_DESIGN "No Guix alice-vision; photogrammetry library at https://github.com/alicevision/AliceVision; C++ cmake + CUDA + extensive deps; very complex; Next: draft cmake recipe with optional CUDA, assess dep tree")
  '(kapowarr NEEDS_RECIPE_DESIGN "No Guix kapowarr; comics management server at https://github.com/Casvt/Kapowarr; Python; needs python recipe + optional Docker; Next: pin version, draft python recipe")
  '(feather-tk NEEDS_RECIPE_DESIGN "No Guix feather-tk; media toolkit at https://github.com/darbyjohnston/feather-tk; C++ cmake; Next: fetch source, draft cmake recipe")
  '(tl-render NEEDS_RECIPE_DESIGN "No Guix tl-render; timeline renderer (likely related to tlRender/OpenTimelineIO); C++ cmake; Next: confirm upstream, fetch source, draft cmake recipe")
  '(sq-bin NEEDS_RECIPE_DESIGN "No Guix sq-bin; sq database CLI tool binary at https://github.com/neilotoole/sq/releases; Go binary; Next: fetch binary, compute hash, draft binary wrapper recipe")
  '(mynav-bin NEEDS_RECIPE_DESIGN "No Guix mynav; navigation utility binary; AUR votes=1; sparse info; Next: check AUR PKGBUILD for upstream URL, assess language/build system")
  '(whosthere-bin NEEDS_RECIPE_DESIGN "No Guix whosthere; network presence tool binary; AUR votes=1; Next: identify upstream repo, fetch binary, compute hash")
  '(phc-intel-dkms-stable NEEDS_RECIPE_DESIGN "No Guix phc-intel; PHC Intel undervolting DKMS module at https://github.com/linux-phc/phc-intel; needs linux-module recipe with kernel ABI pinning; Next: draft linux-module recipe")
  '(pairux-bin NEEDS_RECIPE_DESIGN "No Guix pairux; Bluetooth pairing utility binary; AUR votes=1; Next: check AUR PKGBUILD for upstream URL, fetch binary, compute hash")
  '(plenti-bin NEEDS_RECIPE_DESIGN "No Guix plenti; Go-based static site generator binary at https://github.com/plentico/plenti; needs Go binary or go-build-system recipe; Next: pin version, fetch source, draft go recipe")
  '(zombie NEEDS_RECIPE_DESIGN "No Guix zombie; ambiguous project name; AUR votes=1; Next: check AUR PKGBUILD to confirm which zombie project this refers to")
  '(python-bencoding NEEDS_RECIPE_DESIGN "No Guix python-bencoding; PyPI https://pypi.org/project/bencoding/; bencode encode/decode; needs python-build-system recipe; Next: fetch from PyPI, compute hash, draft python recipe")
  '(sizeof NEEDS_RECIPE_DESIGN "No Guix sizeof; CLI tool printing sizeof for C types; AUR votes=1; C/Makefile trivial; Next: check upstream, draft make-build-system recipe")
  '(template NEEDS_RECIPE_DESIGN "No Guix template (AUR); scaffolding template tool; AUR votes=1; unclear upstream; Next: check AUR PKGBUILD for correct upstream URL")
  '(git-switcher-bin NEEDS_RECIPE_DESIGN "No Guix git-switcher; binary at GitHub releases; Next: confirm upstream URL, fetch binary, compute hash")
  '(cls NEEDS_RECIPE_DESIGN "No Guix cls; command-line tool (ambiguous); AUR votes=1; Next: check AUR PKGBUILD to identify upstream")
  '(eso-addons-manager-bin NEEDS_RECIPE_DESIGN "No Guix eso-addons-manager; ESO (Elder Scrolls Online) addon manager binary; needs binary wrapper; Next: locate stable binary release, draft binary recipe")
  '(eso-addons-manager NEEDS_RECIPE_DESIGN "No Guix eso-addons-manager; ESO addon manager source variant; Next: assess build system from AUR PKGBUILD")
  '(grepai-bin NEEDS_RECIPE_DESIGN "No Guix grepai; AI-assisted grep binary; AUR votes=1; Next: locate upstream repo, fetch binary, compute hash")
  '(cutieascii NEEDS_RECIPE_DESIGN "No Guix cutieascii; ASCII art tool; AUR votes=1; Next: check AUR PKGBUILD for upstream URL and language")
  '(lumus NEEDS_RECIPE_DESIGN "No Guix lumus; ambiguous project; AUR votes=1; Next: check AUR PKGBUILD for correct upstream")
  '(cake-wallet-bin NEEDS_RECIPE_DESIGN "No Guix cake-wallet; cryptocurrency wallet binary at https://github.com/cake-tech/cake_wallet/releases; Flutter/Dart binary; needs binary wrapper with patchelf; Next: fetch Linux binary, compute hash, draft binary recipe")
  '(jdk25-graalvm-bin NEEDS_RECIPE_DESIGN "No Guix jdk25-graalvm-bin; GraalVM JDK 25 binary at https://github.com/graalvm/graalvm-ce-builds/releases; large JVM binary; needs binary wrapper + patchelf; Next: fetch tarball, compute hash, draft binary recipe")
  '(jdk25-graalvm-ce-bin NEEDS_RECIPE_DESIGN "No Guix jdk25-graalvm-ce-bin; GraalVM Community Edition JDK 25 binary; same upstream as above; Next: differentiate CE vs EE, draft binary recipe")
  '(noxdir-bin NEEDS_RECIPE_DESIGN "No Guix noxdir; directory navigation binary; AUR votes=1; Next: check AUR PKGBUILD for upstream URL, language, and binary distribution")
  '(python-requirements-language-server NEEDS_RECIPE_DESIGN "No Guix python-requirements-language-server; LSP for requirements.txt at https://github.com/nicowillis/requirements-language-server or similar; needs python recipe; Next: confirm upstream, fetch, draft python recipe")
  '(sigscan-bin NEEDS_RECIPE_DESIGN "No Guix sigscan; binary signature scanner; AUR votes=1; Next: locate upstream, fetch binary, compute hash")
  '(artisan-roaster-scope NEEDS_RECIPE_DESIGN "No Guix artisan; coffee roasting profile software at https://github.com/artisan-roaster-scope/artisan; Python+PyQt; needs python recipe; Next: pin version, fetch source, draft python recipe")
  '(katifetch NEEDS_RECIPE_DESIGN "No Guix katifetch; system fetch tool; AUR votes=1; likely shell script; Next: check AUR PKGBUILD for upstream URL and install method")
  '(gtk-meshtastic-client NEEDS_RECIPE_DESIGN "No Guix gtk-meshtastic-client; GTK Meshtastic LoRa mesh radio client; C/C++ or Python+GTK; Next: locate upstream repo, assess build system, draft recipe")
  '(linnote NEEDS_RECIPE_DESIGN "No Guix linnote; note-taking app; AUR votes=1; likely Electron or Qt; Next: check AUR PKGBUILD for upstream and build method")
  '(xtatusbar NEEDS_RECIPE_DESIGN "No Guix xtatusbar; X11 status bar; likely C + X11 libs; Next: locate upstream repo, draft recipe")
  '(radiotray-ng NEEDS_RECIPE_DESIGN "No Guix radiotray-ng; internet radio app at https://github.com/ebruck/radiotray-ng; C++ cmake + GTK; Next: pin version, fetch source, draft cmake recipe")
  '(jivexdv-bin NEEDS_RECIPE_DESIGN "No Guix jivexdv; XDV (TeX) viewer binary; AUR votes=1; Next: check AUR PKGBUILD for upstream URL")
  '(zps-bin NEEDS_RECIPE_DESIGN "No Guix zps; process hierarchy browser binary; AUR votes=1; Next: locate upstream, fetch binary, compute hash")
  '(git-incrypt-git NEEDS_RECIPE_DESIGN "No Guix git-incrypt; encrypted git storage tool git version; Next: identify upstream (possibly git-crypt fork), assess build system, draft recipe")
  '(java-service-wrapper NEEDS_RECIPE_DESIGN "No Guix java-service-wrapper; Java Service Wrapper at https://wrapper.tanukisoftware.com/; proprietary binary; LICENSE_REVIEW_NEEDED for Tanuki Software license; Next: review license, fetch binary, draft binary recipe")
  '(tidewave-bin NEEDS_RECIPE_DESIGN "No Guix tidewave-bin; Tidewave Elixir/Phoenix MCP server binary; likely Elixir release; Next: locate binary release URL, compute hash, draft binary recipe")
  '(fsign NEEDS_RECIPE_DESIGN "No Guix fsign; file signing tool; AUR votes=1; Next: check AUR PKGBUILD to identify upstream and build system")
  '(code-minimap-bin NEEDS_RECIPE_DESIGN "No Guix code-minimap; terminal code minimap at https://github.com/wfxr/code-minimap; Rust; binary or cargo recipe; Next: pin version, fetch source, draft cargo recipe")
  '(gpmaster NEEDS_RECIPE_DESIGN "No Guix gpmaster; GPU master tool; AUR votes=1; Next: check AUR PKGBUILD for upstream details")
  '(fackr-bin NEEDS_RECIPE_DESIGN "No Guix fackr; data generation/faker binary; AUR votes=1; Next: identify upstream language and distribution method")
  '(xdgctl-git NEEDS_RECIPE_DESIGN "No Guix xdgctl; XDG control tool git version; Next: locate upstream repo, assess build system, draft recipe")
  '(nijiexpose-bin NEEDS_RECIPE_DESIGN "No Guix nijiexpose; VTuber/camera virtual exposure binary; AUR votes=1; Next: locate stable binary release URL, draft binary recipe")
  '(python-mpris_server NEEDS_RECIPE_DESIGN "No Guix python-mpris-server; Python MPRIS2 server library at https://github.com/poss-org/mpris_server; needs python recipe; Next: fetch from PyPI or GitHub, draft python recipe")
  '(radiotray-ng-mpris NEEDS_RECIPE_DESIGN "No Guix radiotray-ng-mpris; MPRIS2 plugin for radiotray-ng; C++ cmake; same upstream as radiotray-ng; Next: draft cmake recipe after radiotray-ng recipe")
  '(yufi NEEDS_RECIPE_DESIGN "No Guix yufi; application launcher at https://github.com/l4tt3/yufi; Rust; needs cargo recipe; Next: pin version, fetch source, draft cargo recipe")
  '(pgmq NEEDS_RECIPE_DESIGN "No Guix pgmq; Tembo PostgreSQL message queue extension at https://github.com/tembo-io/pgmq; Rust + PostgreSQL extension; needs cargo recipe + pg_extension install; Next: draft cargo recipe with pg_config integration")
  '(prospect-mail NEEDS_RECIPE_DESIGN "No Guix prospect-mail; Outlook/M365 Electron client at https://github.com/julian-alarcon/prospect-mail; Electron binary; needs binary wrapper recipe; Next: fetch release binary, compute hash, draft binary recipe")
  '(goxe NEEDS_RECIPE_DESIGN "No Guix goxe; Go X extension or tool; AUR votes=1; Next: check AUR PKGBUILD for correct upstream URL and build system")
  '(h2status NEEDS_RECIPE_DESIGN "No Guix h2status; HTTP/2 status checker tool; likely Go; Next: locate upstream repo, pin version, draft go recipe")
  '(xattrvi NEEDS_RECIPE_DESIGN "No Guix xattrvi; extended attributes viewer/editor; likely C/ncurses; Next: check AUR PKGBUILD for upstream URL and build system")
  ))
