;;; Blocked notes for queue-20260323p100c queue drain (2026-03-23).
;;; 71 entries blocked with NEEDS_RECIPE_DESIGN or SOURCE_UNAVAILABLE after Guix availability probe.
(define-module (gaurix packages queue-20260323p100c-blocked-notes)
  #:export (queue-20260323p100c-blocked-notes))

(define queue-20260323p100c-blocked-notes
  (list
  '(textern-native-messaging-host NEEDS_RECIPE_DESIGN "No Guix textern; native messaging host at https://github.com/jlebon/textern; trivial-build-system recipe needed; Next: draft install recipe for nm-host binary + manifest.json")
  '(tradingview-bin-latest SOURCE_UNAVAILABLE "TradingView has no permanent binary URL; https://www.tradingview.com/desktop-app redirects via JS; Next: monitor for stable direct-download URL")
  '(css-inline NEEDS_RECIPE_DESIGN "No Guix css-inline; crate at crates.io/crates/css-inline; needs cargo-build-system recipe; Next: pin version, hash, draft cargo recipe")
  '(rjq-bin NEEDS_RECIPE_DESIGN "No Guix rjq; binary at https://github.com/nicowillis/rjq/releases; needs binary or cargo recipe; Next: fetch source tarball, compute hash")
  '(envy-bin NEEDS_RECIPE_DESIGN "No Guix envy; GPU TUI binary; uncertain upstream URL; needs binary wrapper recipe; Next: locate correct upstream, draft binary recipe")
  '(python-funk NEEDS_RECIPE_DESIGN "No Guix python-funk; PyPI https://pypi.org/project/funk/; needs python-build-system recipe; Next: fetch from PyPI, compute hash")
  '(ripsecrets NEEDS_RECIPE_DESIGN "No Guix ripsecrets; source https://github.com/sirwart/ripsecrets; needs cargo-build-system recipe; Next: pin version, fetch source")
  '(rtl8192eu-dkms NEEDS_RECIPE_DESIGN "No Guix rtl8192eu DKMS; source https://github.com/clnhub/rtl8192eu-linux; needs linux-module recipe with kernel ABI pinning; Next: draft linux-module recipe")
  '(process-compose-git NEEDS_RECIPE_DESIGN "No Guix process-compose; source https://github.com/F1bonacc1/process-compose; needs go-build-system recipe; Next: pin git commit, draft go recipe")
  '(ovn NEEDS_RECIPE_DESIGN "No Guix ovn standalone; source https://github.com/ovn-org/ovn; C + autotools + openvswitch dep; Next: draft autotools recipe")
  '(jan-git NEEDS_RECIPE_DESIGN "No Guix jan-git; source https://github.com/janhq/jan; Electron binary; Next: draft Electron binary wrapper recipe")
  '(ryelang-git NEEDS_RECIPE_DESIGN "No Guix ryelang; source https://github.com/refaktorlabor/rye; Go-based; Next: pin commit, draft go-build-system recipe")
  '(python-west NEEDS_RECIPE_DESIGN "No Guix python-west; PyPI https://pypi.org/project/west/; Zephyr RTOS meta-tool; Next: fetch from PyPI, draft python recipe")
  '(basedpyright-git NEEDS_RECIPE_DESIGN "No Guix basedpyright; source https://github.com/DetachHead/basedpyright; Node/npm; Next: pin commit, draft node-build-system recipe")
  '(envy-tui-bin NEEDS_RECIPE_DESIGN "No Guix envy-tui-bin; binary from same upstream as envy-bin; Next: locate stable binary release, draft binary recipe")
  '(ttf-lxgw-neo-xihei NEEDS_RECIPE_DESIGN "No Guix ttf-lxgw-neo-xihei; fonts at https://github.com/lxgw/LxgwNeoXiHei/releases; needs trivial font recipe to $out/share/fonts/truetype; Next: fetch release tarball, compute hash")
  '(ttf-lxgw-neo-xihei-screen NEEDS_RECIPE_DESIGN "No Guix ttf-lxgw-neo-xihei-screen; screen-optimized variant of above; same upstream; Next: draft trivial recipe after sibling")
  '(tonearm NEEDS_RECIPE_DESIGN "No Guix tonearm; unclear upstream (AUR votes=1); Next: identify correct upstream repo, assess build system")
  '(ftb NEEDS_RECIPE_DESIGN "No Guix ftb; Feed the Beast Minecraft launcher; Electron binary at https://www.feed-the-beast.com/; Next: draft binary/AppImage recipe")
  '(dsw-bin NEEDS_RECIPE_DESIGN "No Guix dsw; Data Stewardship Wizard binary at https://github.com/ds-wizard/engine-backend/releases; Next: fetch binary, draft binary wrapper")
  '(river-creek NEEDS_RECIPE_DESIGN "No Guix river-creek; River Wayland utility; likely Rust; Next: identify correct repo, draft cargo recipe")
  '(datui-bin NEEDS_RECIPE_DESIGN "No Guix datui-bin; TUI data viewer binary; AUR votes=1; Next: locate upstream repo, identify language, draft recipe")
  '(happy-cli NEEDS_RECIPE_DESIGN "Guix has haskell-happy but not happy-cli standalone; source https://github.com/sysfce2/haskell-happy; Next: check if CLI binary is already in Guix haskell-happy output")
  '(lib32-python NEEDS_RECIPE_DESIGN "No Guix lib32-python; requires --target=i686-linux cross-compilation of python; arch-specific multilib approach; Next: assess 32-bit cross-compile in Guix")
  '(peertube-gtk-git NEEDS_RECIPE_DESIGN "No Guix peertube-gtk; source https://gitlab.gnome.org/World/PeerTube; Rust+GTK4; Next: pin git commit, draft cargo recipe with gtk4 inputs")
  '(silverr-bin NEEDS_RECIPE_DESIGN "No Guix silverr; unclear upstream; AUR votes=1; Next: investigate AUR PKGBUILD, identify upstream")
  '(duelsplus-bin NEEDS_RECIPE_DESIGN "No Guix duelsplus; game binary; unclear stable source URL; Next: locate stable release channel, draft binary recipe")
  '(square1-wad NEEDS_RECIPE_DESIGN "No Guix square1-wad; DOOM-engine WAD data install; needs trivial recipe installing WAD to share/games/; Next: find authoritative source URL, compute hash")
  '(rexuiz-bin NEEDS_RECIPE_DESIGN "No Guix rexuiz; Xonotic fork binary at https://rexuiz.hockey; needs binary wrapper with patchelf; Next: fetch binary tarball, compute hash")
  '(solv-bin NEEDS_RECIPE_DESIGN "No Guix solv-bin standalone (libsolv exists); verify if this is libsolv CLI or different SAT tool; Next: check AUR PKGBUILD for upstream source")
  '(roundcubemail-plugin-keyboard-shortcuts-ng NEEDS_RECIPE_DESIGN "No Guix roundcubemail plugins; PHP plugin at https://github.com/johndoh/roundcube-keyboard-shortcuts; trivial install to Roundcube plugins dir; Next: draft PHP data-install recipe")
  '(roundcubemail-plugin-chbox NEEDS_RECIPE_DESIGN "No Guix roundcubemail plugins; PHP plugin via Roundcube marketplace; needs trivial install recipe; Next: locate source repo, draft data-install recipe")
  '(adwaita-dark-darose NEEDS_RECIPE_DESIGN "No Guix adwaita-dark-darose; custom GTK theme; source at community repo; needs trivial recipe to $out/share/themes/; Next: locate upstream, draft theme data recipe")
  '(lution NEEDS_RECIPE_DESIGN "No Guix lution; AUR votes=1; sparse AUR info; Next: investigate AUR source to identify upstream and build system")
  '(superdb-bin NEEDS_RECIPE_DESIGN "No Guix superdb; binary from https://github.com/brimdata/zed/releases (Zed suite); needs go or binary recipe; Next: fetch source, verify license, draft recipe")
  '(tmpo-bin NEEDS_RECIPE_DESIGN "No Guix tmpo; temp file management binary (Rust CLI); uncertain upstream URL; Next: locate stable upstream, fetch source, draft cargo recipe")
  '(wheelwizard NEEDS_RECIPE_DESIGN "No Guix wheelwizard; source https://github.com/Wheel-Wizard/WheelWizard; C# Avalonia; needs dotnet-build-system recipe; Next: fetch source, draft dotnet recipe")
  '(rocm-nightly-gfx110x-bin NEEDS_RECIPE_DESIGN "No Guix rocm-nightly; AMD binary at https://repo.radeon.com/rocm/; needs binary recipe with patchelf + udev rules; Next: pin nightly version, draft binary recipe")
  '(datafusion-cli NEEDS_RECIPE_DESIGN "No Guix datafusion-cli; Apache DataFusion source https://github.com/apache/datafusion; needs cargo-build-system recipe for cli crate; Next: pin version, fetch source, draft cargo recipe")
  '(zen-browser-git NEEDS_RECIPE_DESIGN "No Guix zen-browser; source https://github.com/zen-browser/desktop; Firefox/Rust complex build; needs moz-configure-based recipe following icecat pattern; Next: assess build system, draft recipe")
  '(nwdiag NEEDS_RECIPE_DESIGN "No Guix nwdiag; PyPI https://pypi.org/project/nwdiag/; blockdiag family; needs python-build-system recipe; Next: fetch from PyPI, draft python recipe")
  '(actdiag NEEDS_RECIPE_DESIGN "No Guix actdiag; PyPI https://pypi.org/project/actdiag/; blockdiag family; needs python-build-system recipe; Next: fetch from PyPI, draft python recipe")
  '(python-importmonkey NEEDS_RECIPE_DESIGN "No Guix python-importmonkey; PyPI https://pypi.org/project/importmonkey/; needs python-build-system recipe; Next: fetch from PyPI, compute hash, draft recipe")
  '(vm-curator NEEDS_RECIPE_DESIGN "No Guix vm-curator; unclear upstream (AUR votes=1); Next: identify upstream repo, draft recipe")
  '(open-in-native-client NEEDS_RECIPE_DESIGN "No Guix open-in-native-client; native messaging host binary + browser manifest; Next: locate upstream, draft trivial install recipe")
  '(pnana NEEDS_RECIPE_DESIGN "No Guix pnana; AUR information sparse; votes=1; Next: investigate AUR PKGBUILD to identify upstream")
  '(clight NEEDS_RECIPE_DESIGN "No Guix clight; source https://github.com/FedeDP/Clight; C cmake + dbus + clightd dep; needs cmake recipe; Next: fetch source, draft cmake recipe")
  '(udever-git NEEDS_RECIPE_DESIGN "No Guix udever; USB device event recorder; git version; Next: locate upstream, assess build system, draft recipe")
  '(pomo-bin NEEDS_RECIPE_DESIGN "No Guix pomo; Pomodoro timer Go binary at https://github.com/kevinschoon/pomo; needs go-build-system recipe; Next: pin version, fetch source, draft go recipe")
  '(tmmpr-bin NEEDS_RECIPE_DESIGN "No Guix tmmpr; AUR votes=1; purpose unclear; Next: investigate AUR PKGBUILD for upstream source")
  '(sayonara-player NEEDS_RECIPE_DESIGN "No Guix sayonara-player; source https://github.com/Sayonara-Player/Sayonara; C++ cmake + Qt5/6; Next: fetch release tarball, compute hash, draft cmake recipe")
  '(wafw00f NEEDS_RECIPE_DESIGN "No Guix wafw00f; WAF detection tool at https://github.com/EnableSecurity/wafw00f; Python; needs python-build-system recipe; Next: fetch from PyPI/GitHub, draft recipe")
  '(telegram-tdlib-purple-git NEEDS_RECIPE_DESIGN "No Guix telegram-tdlib-purple; source https://github.com/BenWiederhake/tdlib-purple; C++ cmake + tdlib dep; Next: fetch source, pin tdlib version, draft cmake recipe")
  '(apifox-appimage NEEDS_RECIPE_DESIGN "No Guix apifox; proprietary Electron AppImage at https://apifox.com/; needs binary AppImage wrapper with patchelf; Next: fetch AppImage, compute hash, draft binary recipe")
  '(3dstool-git NEEDS_RECIPE_DESIGN "No Guix 3dstool; source https://github.com/dnasdw/3dstool; C++ cmake; Next: pin commit, fetch source, draft cmake recipe")
  '(python-qiskit-gym NEEDS_RECIPE_DESIGN "No Guix python-qiskit-gym; quantum RL gym; PyPI https://pypi.org/project/qiskit-gym/; Next: fetch from PyPI, draft python recipe with qiskit deps")
  '(rustfetch-git NEEDS_RECIPE_DESIGN "No Guix rustfetch; neofetch-like Rust tool; git version; Next: locate stable upstream, pin commit, draft cargo recipe")
  '(h2status-git NEEDS_RECIPE_DESIGN "No Guix h2status; HTTP/2 status checker; git version; likely Go or Rust; Next: locate upstream, assess build system, draft recipe")
  '(tlclient NEEDS_RECIPE_DESIGN "No Guix tlclient; ThinLinc proprietary remote desktop client at https://www.cendio.com/thinlinc/download; needs binary wrapper recipe; Next: fetch installer, extract, draft binary recipe")
  '(libpurple-lurch-git NEEDS_RECIPE_DESIGN "No Guix libpurple-lurch; OMEMO encryption plugin at https://github.com/gkdr/lurch; C cmake + libsignal-protocol dep; Next: fetch source, draft cmake recipe")
  '(sticker-convert NEEDS_RECIPE_DESIGN "No Guix sticker-convert; PyPI https://pypi.org/project/sticker-convert/; Python + ffmpeg/pillow deps; Next: fetch from PyPI, compute hash, draft python recipe")
  '(zectl NEEDS_RECIPE_DESIGN "No Guix zectl; ZFS boot env manager at https://github.com/johnramsden/zectl; Python; needs python recipe + zfs dep; Next: fetch from PyPI or GitHub, draft python recipe")
  '(mov-watch NEEDS_RECIPE_DESIGN "No Guix mov-watch; file system watch/move tool; AUR votes=1; Next: investigate AUR PKGBUILD to identify upstream and build system")
  '(eddie-cli NEEDS_RECIPE_DESIGN "No Guix eddie-cli; AirVPN client CLI at https://github.com/AirVPN/Eddie; C# dotnet; needs dotnet-build-system recipe; Next: fetch source, draft dotnet recipe")
  '(pam-luks-keyring-unlock NEEDS_RECIPE_DESIGN "No Guix pam-luks-keyring-unlock; PAM module for LUKS + keyring; C + PAM; needs make-build-system recipe with linux-pam dep; Next: locate upstream, fetch source, draft recipe")
  '(ani-rss NEEDS_RECIPE_DESIGN "No Guix ani-rss; RSS aggregator for anime; unclear upstream language; Next: investigate AUR PKGBUILD, locate upstream repo, draft recipe")
  '(lazylibrarian-git NEEDS_RECIPE_DESIGN "No Guix lazylibrarian; source https://gitlab.com/lazylibrarian/LazyLibrarian; Python web app; Next: pin git commit, draft python recipe")
  '(outline-client-appimage NEEDS_RECIPE_DESIGN "No Guix outline-client; Jigsaw/Google VPN AppImage at https://getoutline.org/; Electron binary; needs AppImage wrapper with patchelf; Next: fetch AppImage, compute hash, draft binary recipe")
  '(monika-after-story-bin NEEDS_RECIPE_DESIGN "No Guix monika-after-story; DDLC mod Ren'Py binary at https://monikaafterstory.com/releases.html; LICENSE_REVIEW_NEEDED for DDLC base assets; Next: fetch binary, draft binary recipe, review license compatibility")
  '(sdbus-cpp-basu-git NEEDS_RECIPE_DESIGN "No Guix sdbus-cpp-basu; sdbus-cpp with basu sd-bus at https://github.com/Kistler-Group/sdbus-cpp; C++ cmake + elogind/basu dep; Next: fetch source, draft cmake recipe")
  '(clion-eap NEEDS_RECIPE_DESIGN "No Guix clion; proprietary JetBrains CLion EAP at https://www.jetbrains.com/clion/nextversion/; LICENSE_REVIEW_NEEDED for JetBrains EAP EULA; needs binary wrapper with JVM + patchelf; Next: fetch EAP tarball, compute hash, draft binary recipe")
  ))
