;;; Notes for queue drain blockers (recipe-design stubs).
(define-module (gaurix packages queue-20260321p100-blocked-notes)
  #:export (queue-20260321p100-blocked-recipes))

(define queue-20260321p100-blocked-recipes
  '(
    (rapidraw NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (tuxedo-drivers-dkms NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (steamtinkerlaunch NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (libva-vdpau-driver NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (weasis-bin NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (protonhax NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (p7zip-gui NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (yed NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (anyrun NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (zenmonitor3-git NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (unigine-heaven NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (breitbandmessung-bin NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (ancient-packages NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (overdue NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (tidal-hifi NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (marp-cli NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (adwaita-qt5-git NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (adwaita-qt6-git NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (ssacli-bin NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (tuxboot NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (amdfand-bin NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (scratch3-bin NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (libstdc++5-bin NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (ezstream NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (cevomapgen NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (slippi-launcher-bin NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (radicle-node NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (xdg-su NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
    (python-markovify NEEDS_RECIPE_DESIGN "No direct Guix equivalent in this pass; requires dedicated recipe draft.")
  ))
