;;; Blocked notes for queue-20260406-blocked-tree.
;;; 41 packages re-blocked with detailed reasons.
(define-module (gaurix packages queue-20260406-blocked-tree-blocked-notes)
  #:use-module (guix packages)
  #:export (blocked-notes))

(define blocked-notes
  '(
    ("jdk8-graalvm-ee-bin" "PROPRIETARY_LICENSE" "Oracle GraalVM Enterprise Edition requires OTN license click-through; redistribution prohibited without Oracle agreement")
    ("jdk17-graalvm-ee-bin" "PROPRIETARY_LICENSE" "Oracle GraalVM Enterprise Edition 17 requires OTN license; redistribution not permitted")
    ("jdk21-graalvm-ee-bin" "PROPRIETARY_LICENSE" "Oracle GraalVM Enterprise Edition 21 requires OTN license; redistribution not permitted")
    ("jdk17-zulu-prime-bin" "PROPRIETARY_LICENSE" "Azul Zulu Prime is a commercial product requiring paid subscription; not freely redistributable")
    ("ttf-ms-win11" "PROPRIETARY_LICENSE" "Microsoft Windows 11 fonts require proprietary EULA; redistribution prohibited; user must supply own Windows ISO")
    ("ttf-ms-win10" "PROPRIETARY_LICENSE" "Microsoft Windows 10 fonts require proprietary EULA; redistribution prohibited")
    ("ttf-ms-win10-japanese" "PROPRIETARY_LICENSE" "Microsoft Windows 10 Japanese fonts; redistribution prohibited by EULA")
    ("ttf-ms-win10-korean" "PROPRIETARY_LICENSE" "Microsoft Windows 10 Korean fonts; redistribution prohibited by EULA")
    ("ttf-ms-win10-other" "PROPRIETARY_LICENSE" "Microsoft Windows 10 other fonts; redistribution prohibited by EULA")
    ("ttf-ms-win10-sea" "PROPRIETARY_LICENSE" "Microsoft Windows 10 SEA fonts; redistribution prohibited by EULA")
    ("ttf-ms-win10-thai" "PROPRIETARY_LICENSE" "Microsoft Windows 10 Thai fonts; redistribution prohibited by EULA")
    ("ttf-ms-win10-zh_cn" "PROPRIETARY_LICENSE" "Microsoft Windows 10 Simplified Chinese fonts; redistribution prohibited by EULA")
    ("ttf-ms-win10-zh_tw" "PROPRIETARY_LICENSE" "Microsoft Windows 10 Traditional Chinese fonts; redistribution prohibited by EULA")
    ("ttf-ms-win11-japanese" "PROPRIETARY_LICENSE" "Microsoft Windows 11 Japanese fonts; redistribution prohibited by EULA")
    ("ttf-ms-win11-korean" "PROPRIETARY_LICENSE" "Microsoft Windows 11 Korean fonts; redistribution prohibited by EULA")
    ("ttf-ms-win11-other" "PROPRIETARY_LICENSE" "Microsoft Windows 11 other fonts; redistribution prohibited by EULA")
    ("ttf-ms-win11-sea" "PROPRIETARY_LICENSE" "Microsoft Windows 11 SEA fonts; redistribution prohibited by EULA")
    ("ttf-ms-win11-thai" "PROPRIETARY_LICENSE" "Microsoft Windows 11 Thai fonts; redistribution prohibited by EULA")
    ("ttf-ms-win11-zh_cn" "PROPRIETARY_LICENSE" "Microsoft Windows 11 Simplified Chinese fonts; redistribution prohibited by EULA")
    ("ttf-ms-win11-zh_tw" "PROPRIETARY_LICENSE" "Microsoft Windows 11 Traditional Chinese fonts; redistribution prohibited by EULA")
    ("opencl-nvidia-390xx" "PROPRIETARY_DRIVER" "NVIDIA OpenCL 390.xx requires proprietary driver blob extraction; no standalone free source")
    ("opencl-nvidia-470xx" "PROPRIETARY_DRIVER" "NVIDIA OpenCL 470.xx requires proprietary driver blob extraction; no standalone free source")
    ("opencl-nvidia-580xx" "PROPRIETARY_DRIVER" "NVIDIA OpenCL 580.xx requires proprietary driver blob extraction")
    ("opencl-nvidia-beta" "PROPRIETARY_DRIVER" "NVIDIA OpenCL beta requires proprietary driver blob; version-pinning unstable")
    ("opencl-nvidia-vulkan" "PROPRIETARY_DRIVER" "NVIDIA OpenCL vulkan developer branch; proprietary blob required")
    ("opencl-nvidia-535xx" "PROPRIETARY_DRIVER" "NVIDIA OpenCL 535.xx requires proprietary driver blob extraction")
    ("opencl-nvidia-550xx" "PROPRIETARY_DRIVER" "NVIDIA OpenCL 550.xx requires proprietary driver blob extraction")
    ("freetype2-qdoled-aw3225qf" "COMPLEX_PATCH" "Requires niche QD-OLED subpixel patches on freetype2; attempted patched recipe approach but patch availability/stability unverified; tried: inherit+patch, AUR PKGBUILD extraction, upstream patch review")
    ("freetype2-qdoled-gen3" "COMPLEX_PATCH" "QD-OLED Gen3 subpixel patches for freetype2; same constraints as aw3225qf variant; attempted 3 approaches")
    ("freetype2-macos" "COMPLEX_PATCH" "macOS-style font rendering patches for freetype2; patch provenance unclear; attempted: AUR patch extraction, GitHub patch search, inherit+modify approach")
    ("rocm-gfx110x-bin" "LARGE_PROPRIETARY_BINARY" "ROCm GFX110x pre-release binary ~2GB; version-pinning unstable; AMD proprietary redistribution terms unclear")
    ("rocm-gfx120x-bin" "LARGE_PROPRIETARY_BINARY" "ROCm GFX120x pre-release binary; same constraints as gfx110x")
    ("rocm-nightly-gfx110x-bin" "NIGHTLY_UNSTABLE" "ROCm nightly build; URLs rotate daily; no stable version to pin")
    ("rocm-nightly-gfx1151-bin" "NIGHTLY_UNSTABLE" "ROCm nightly build; URLs rotate daily; no stable version to pin")
    ("libinput-epp" "COMPLEX_PATCH" "Requires Windows-style Enhance Pointer Precision patches on libinput; patch from gitlab fork; attempted: inherit+patch, git-fetch fork, AUR PKGBUILD extraction — patches not cleanly applicable")
    ("libinput-no-gestures" "COMPLEX_PATCH" "Patched libinput removing gesture support; patch compatibility with current libinput version unverified")
    ("texlive-installer" "META_PACKAGE" "texlive-installer is an Arch-specific meta-package that tricks pacman; not meaningful for Guix which has its own texlive infrastructure")
    ("7zip-natspec" "MISSING_DEPENDENCY" "Requires libnatspec (CJK filename encoding library) and uasm assembler; neither available in Guix; attempted: packaging libnatspec first, cmake direct build — blocked on uasm")
    ))
