;;; Queue drain 2026-04-03 daily run batch 4.
;;; Attempted 100 TODO-status entries from todo_general_packages.org.
;;; Status: 1 new package recipe validated; 99 recipe drafts/blockers recorded separately.
(define-module (gaurix packages queue-20260403p100daily4)
  #:use-module (guix download)
  #:use-module (guix git-download)
  #:use-module (guix packages)
  #:use-module (guix build-system pyproject)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (gnu packages python-build)
  #:use-module (gnu packages python-xyz)
  #:use-module (gnu packages xml)
  #:export (python-pptx
            queue-20260403p100daily4-recipe-drafts))

(define-public python-pptx
  (package
    (name "python-pptx")
    (version "1.0.2")
    (source
     (origin
       (method git-fetch)
       (uri (git-reference
             (url "https://github.com/scanny/python-pptx")
             (commit (string-append "v" version))))
       (file-name (git-file-name name version))
       (sha256
        (base32 "1g7bb4iqpbl5r6fw3fzbfzhpxq252y6ss79n7qawngrd62sns81b"))))
    (build-system pyproject-build-system)
    (propagated-inputs
     (list python-lxml
           python-pillow
           python-typing-extensions
           python-xlsxwriter))
    (native-inputs (list python-setuptools python-wheel))
    (home-page "https://github.com/scanny/python-pptx")
    (synopsis "Create, read, and update PowerPoint 2007+ (.pptx) files")
    (description
     "python-pptx creates, reads, and updates PowerPoint 2007+ .pptx files.")
    (license license:expat)))

(define-public queue-20260403p100daily4-recipe-drafts
  '(("python-pptx" "completed")
    ("factorio" "draft-started")
    ("xemu-bin" "draft-started")
    ("windscribe-v2-bin" "draft-started")
    ("droidcam-obs-plugin-git" "draft-started")
    ("wsl2-ssh-agent" "draft-started")
    ("filkoll" "draft-started")
    ("stable-diffusion.cpp-vulkan-git" "draft-started")
    ("kde-service-menu-reimage-mod" "draft-started")
    ("vgmstream-cli-bin" "draft-started")
    ("0ad-zh-lang" "draft-started")
    ("boomaga" "draft-started")
    ("grpcurl" "draft-started")
    ("rtl8851bu-dkms-git" "draft-started")
    ("xnconvert" "draft-started")
    ("ttf-poppins" "draft-started")
    ("pacman-hook-bootbackup" "draft-started")
    ("flatpost" "draft-started")
    ("numaplayer" "draft-started")
    ("beautyline" "draft-started")
    ("flac2all" "draft-started")
    ("chatwise" "draft-started")
    ("uutils-diffutils" "draft-started")
    ("acroread-fonts-systemwide" "draft-started")
    ("motrix-bin" "draft-started")
    ("rtl8188gu-dkms-git" "draft-started")
    ("loot" "draft-started")
    ("cosmic-player-git" "draft-started")
    ("cosmic-store-git" "draft-started")
    ("alpaca-ai" "draft-started")
    ("vr-video-player" "draft-started")
    ("hunspell-sr" "draft-started")
    ("losslesscut-git" "draft-started")
    ("uutils-util-linux-git" "draft-started")
    ("uutils-hostname-git" "draft-started")
    ("uutils-procps-git" "draft-started")
    ("uutils-sed-git" "draft-started")
    ("wayfreeze-git" "draft-started")
    ("bleachbit-root" "draft-started")
    ("vencord-bin" "draft-started")
    ("chromium-vencord-bin" "draft-started")
    ("firefox-vencord-bin" "draft-started")
    ("firefox-developer-edition-vencord-bin" "draft-started")
    ("librewolf-vencord-bin" "draft-started")
    ("bootstrap-studio" "draft-started")
    ("warsaw-bin" "draft-started")
    ("deltaclient-git" "draft-started")
    ("forticlient-vpn" "draft-started")
    ("nrfutil" "draft-started")
    ("cubiomes-viewer" "draft-started")
    ("aqemu" "draft-started")
    ("iceshrimp.net" "draft-started")
    ("qlcplus" "draft-started")
    ("uqm-megamod-git" "draft-started")
    ("arm-linux-gnueabihf-linux-api-headers" "draft-started")
    ("arm-linux-gnueabihf-glibc" "draft-started")
    ("arm-linux-gnueabihf-gcc-stage2" "draft-started")
    ("fred" "draft-started")
    ("apple-sf-script-extension-fonts" "draft-started")
    ("tek" "draft-started")
    ("pdf-xchange" "draft-started")
    ("vinegar-git" "draft-started")
    ("longbridge-pro-appimage" "draft-started")
    ("pk_web-git" "draft-started")
    ("meocloud-cli" "draft-started")
    ("subcat-git" "draft-started")
    ("wappalyzer-next-git" "draft-started")
    ("flclashx-git" "draft-started")
    ("rawbit" "draft-started")
    ("shsh" "draft-started")
    ("aur-auto" "draft-started")
    ("bitcomet" "draft-started")
    ("cline-cli" "draft-started")
    ("swayshot" "draft-started")
    ("ttf-mac-fonts" "draft-started")
    ("nautilus-metadata-editor" "draft-started")
    ("openhardwaremonitor" "draft-started")
    ("overte-appimage" "draft-started")
    ("vrcx-nightly-bin" "draft-started")
    ("xyvr" "draft-started")
    ("python-minotaur-git" "draft-started")
    ("rtl8852cu-dkms-morrownr-git" "draft-started")
    ("smithery-cli" "draft-started")
    ("netease-cloud-music-wine" "draft-started")
    ("waydroidsu" "draft-started")
    ("linux-firewire-utils" "draft-started")
    ("opcode-bin" "draft-started")
    ("uutils-tar-git" "draft-started")
    ("ttf-alte-haas-grotesk" "draft-started")
    ("thinkmorse" "draft-started")
    ("dbmodel-qt5" "draft-started")
    ("waybar-weather" "draft-started")
    ("kurtosis-cli-bin" "draft-started")
    ("libcanberra-gtk2" "draft-started")
    ("ruby-flexmock" "draft-started")
    ("ddgst-bin" "draft-started")
    ("zfsbackrest-bin" "draft-started")
    ("ddhx-bin" "draft-started")
    ("firefly-iii-data-importer" "draft-started")
    ("mcp-gearbox-bin" "draft-started")
    ))
