;;; Blocked notes for 2026-03-22 p100e queue drain.
(define-module (gaurix packages queue-20260322p100e-blocked-notes)
  #:export (queue-20260322p100e-blocked))

(define queue-20260322p100e-blocked
  '(
    ("socialstreamninja-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['socialstreamninja-bin', 'socialstreamninja']; next action: draft fresh recipe from upstream source in next pass.")
    ("rustwhy-git" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['rustwhy-git', 'rustwhy']; next action: draft fresh recipe from upstream source in next pass.")
    ("bar_daemon" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['bar_daemon', 'bar-daemon']; next action: draft fresh recipe from upstream source in next pass.")
    ("carbonyl" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['carbonyl']; next action: draft fresh recipe from upstream source in next pass.")
    ("pipewire-audio-idle-inhibit-git" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['pipewire-audio-idle-inhibit-git', 'pipewire-audio-idle-inhibit']; next action: draft fresh recipe from upstream source in next pass.")
    ("oyasumi-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['oyasumi-bin', 'oyasumi']; next action: draft fresh recipe from upstream source in next pass.")
    ("mcp-cli-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['mcp-cli-bin', 'mcp-cli', 'mcpcli']; next action: draft fresh recipe from upstream source in next pass.")
    ("matcha-client-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['matcha-client-bin', 'matcha-client', 'matchaclient']; next action: draft fresh recipe from upstream source in next pass.")
    ("ggml-sycl-f16-git" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['ggml-sycl-f16-git', 'ggml-sycl-f16']; next action: draft fresh recipe from upstream source in next pass.")
    ("most-snapshot" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['most-snapshot']; next action: draft fresh recipe from upstream source in next pass.")
    ("signalbackup-tools-git" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['signalbackup-tools-git', 'signalbackup-tools']; next action: draft fresh recipe from upstream source in next pass.")
    ("continuwuity-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['continuwuity-bin', 'continuwuity']; next action: draft fresh recipe from upstream source in next pass.")
    ("hyprquickframe-git" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['hyprquickframe-git', 'hyprquickframe']; next action: draft fresh recipe from upstream source in next pass.")
    ("ride-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['ride-bin', 'ride']; next action: draft fresh recipe from upstream source in next pass.")
    ("bridge-core-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['bridge-core-bin', 'bridge-core', 'bridgecore']; next action: draft fresh recipe from upstream source in next pass.")
    ("ahab-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['ahab-bin', 'ahab']; next action: draft fresh recipe from upstream source in next pass.")
    ("ibus-autostart-kimpanel" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['ibus-autostart-kimpanel']; next action: draft fresh recipe from upstream source in next pass.")
    ("crystal-nightly" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['crystal-nightly', 'crystal']; next action: draft fresh recipe from upstream source in next pass.")
    ("scantool-git" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['scantool-git', 'scantool']; next action: draft fresh recipe from upstream source in next pass.")
    ("rexit-git" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['rexit-git', 'rexit']; next action: draft fresh recipe from upstream source in next pass.")
    ("tuack-ng-git" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['tuack-ng-git', 'tuack-ng']; next action: draft fresh recipe from upstream source in next pass.")
    ("github-account-switch-git" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['github-account-switch-git', 'github-account-switch']; next action: draft fresh recipe from upstream source in next pass.")
    ("alix-git" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['alix-git', 'alix']; next action: draft fresh recipe from upstream source in next pass.")
    ("azd-cli" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['azd-cli', 'azd']; next action: draft fresh recipe from upstream source in next pass.")
    ("dooble-git" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['dooble-git', 'dooble']; next action: draft fresh recipe from upstream source in next pass.")
    ("qfinderpro-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['qfinderpro-bin', 'qfinderpro']; next action: draft fresh recipe from upstream source in next pass.")
    ("xfr-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['xfr-bin', 'xfr']; next action: draft fresh recipe from upstream source in next pass.")
    ("yauri" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['yauri']; next action: draft fresh recipe from upstream source in next pass.")
    ("konform-browser-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['konform-browser-bin', 'konform-browser', 'konformbrowser']; next action: draft fresh recipe from upstream source in next pass.")
    ("odzip" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['odzip']; next action: draft fresh recipe from upstream source in next pass.")
    ("scrapfetch-git" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['scrapfetch-git', 'scrapfetch']; next action: draft fresh recipe from upstream source in next pass.")
    ("gosuki" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['gosuki']; next action: draft fresh recipe from upstream source in next pass.")
    ("lolcat++-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['lolcat++-bin', 'lolcat++']; next action: draft fresh recipe from upstream source in next pass.")
    ("qatlib" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['qatlib']; next action: draft fresh recipe from upstream source in next pass.")
    ("bsky-electron-git" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['bsky-electron-git', 'bsky-electron']; next action: draft fresh recipe from upstream source in next pass.")
    ("lolcat++" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['lolcat++']; next action: draft fresh recipe from upstream source in next pass.")
    ("archforge-git" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['archforge-git', 'archforge']; next action: draft fresh recipe from upstream source in next pass.")
    ("pj-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['pj-bin', 'pj']; next action: draft fresh recipe from upstream source in next pass.")
    ("valent" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['valent']; next action: draft fresh recipe from upstream source in next pass.")
    ("reef" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['reef']; next action: draft fresh recipe from upstream source in next pass.")
    ("reef-tools" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['reef-tools']; next action: draft fresh recipe from upstream source in next pass.")
    ("kclock-rs-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['kclock-rs-bin', 'kclock-rs', 'kclockrs']; next action: draft fresh recipe from upstream source in next pass.")
    ("ttl-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['ttl-bin', 'ttl']; next action: draft fresh recipe from upstream source in next pass.")
    ("dyalog-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['dyalog-bin', 'dyalog']; next action: draft fresh recipe from upstream source in next pass.")
    ("rime-nushu" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['rime-nushu']; next action: draft fresh recipe from upstream source in next pass.")
    ("thorium-browser-avx-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['thorium-browser-avx-bin', 'thorium-browser-avx', 'thoriumbrowseravx']; next action: draft fresh recipe from upstream source in next pass.")
    ("konfyt" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['konfyt']; next action: draft fresh recipe from upstream source in next pass.")
    ("python-textual-fspicker-git" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['python-textual-fspicker-git', 'python-textual-fspicker']; next action: draft fresh recipe from upstream source in next pass.")
    ("hfdownloader-git" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['hfdownloader-git', 'hfdownloader']; next action: draft fresh recipe from upstream source in next pass.")
    ("tomcat8" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['tomcat8']; next action: draft fresh recipe from upstream source in next pass.")
    ("bbdown-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['bbdown-bin', 'bbdown']; next action: draft fresh recipe from upstream source in next pass.")
    ("crier" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['crier']; next action: draft fresh recipe from upstream source in next pass.")
    ("hardbore" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['hardbore']; next action: draft fresh recipe from upstream source in next pass.")
    ("hardbore-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['hardbore-bin', 'hardbore']; next action: draft fresh recipe from upstream source in next pass.")
    ("proc-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['proc-bin', 'proc']; next action: draft fresh recipe from upstream source in next pass.")
    ("xc-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['xc-bin', 'xc']; next action: draft fresh recipe from upstream source in next pass.")
    ("fsid" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['fsid']; next action: draft fresh recipe from upstream source in next pass.")
    ("upi" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['upi']; next action: draft fresh recipe from upstream source in next pass.")
    ("gasroot" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['gasroot']; next action: draft fresh recipe from upstream source in next pass.")
    ("spacebar-client-git" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['spacebar-client-git', 'spacebar-client']; next action: draft fresh recipe from upstream source in next pass.")
    ("spacebar-git" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['spacebar-git', 'spacebar']; next action: draft fresh recipe from upstream source in next pass.")
    ("vatomic" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['vatomic']; next action: draft fresh recipe from upstream source in next pass.")
    ("wtp" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['wtp']; next action: draft fresh recipe from upstream source in next pass.")
    ("zerobrew-git" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['zerobrew-git', 'zerobrew']; next action: draft fresh recipe from upstream source in next pass.")
    ("zerobrew-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['zerobrew-bin', 'zerobrew']; next action: draft fresh recipe from upstream source in next pass.")
    ("bus" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['bus']; next action: draft fresh recipe from upstream source in next pass.")
    ("alarm" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['alarm']; next action: draft fresh recipe from upstream source in next pass.")
    ("tchap-desktop" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['tchap-desktop', 'tchap']; next action: draft fresh recipe from upstream source in next pass.")
    ("alacritty-nox-git" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['alacritty-nox-git', 'alacritty-nox']; next action: draft fresh recipe from upstream source in next pass.")
    ("codelldb" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['codelldb']; next action: draft fresh recipe from upstream source in next pass.")
    ("asroot" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['asroot']; next action: draft fresh recipe from upstream source in next pass.")
    ("pseint" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['pseint']; next action: draft fresh recipe from upstream source in next pass.")
    ("clipsync-git" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['clipsync-git', 'clipsync']; next action: draft fresh recipe from upstream source in next pass.")
    ("wiso-steuer-2026" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['wiso-steuer-2026', 'wiso-steuer']; next action: draft fresh recipe from upstream source in next pass.")
    ("tmodloader-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['tmodloader-bin', 'tmodloader']; next action: draft fresh recipe from upstream source in next pass.")
    ("dolphin-anty-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['dolphin-anty-bin', 'dolphin-anty', 'dolphinanty']; next action: draft fresh recipe from upstream source in next pass.")
    ("pp" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['pp']; next action: draft fresh recipe from upstream source in next pass.")
    ("surge" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['surge']; next action: draft fresh recipe from upstream source in next pass.")
    ("katana-mk2-fxfloorboard-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['katana-mk2-fxfloorboard-bin', 'katana-mk2-fxfloorboard', 'katanamk2fxfloorboard']; next action: draft fresh recipe from upstream source in next pass.")
    ("xcman" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['xcman']; next action: draft fresh recipe from upstream source in next pass.")
    ("grab-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['grab-bin', 'grab']; next action: draft fresh recipe from upstream source in next pass.")
    ("music-assistant-desktop-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['music-assistant-desktop-bin', 'music-assistant-desktop', 'musicassistantdesktop']; next action: draft fresh recipe from upstream source in next pass.")
    ("borse" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['borse']; next action: draft fresh recipe from upstream source in next pass.")
    ("xapp-appimage-thumbnailer" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['xapp-appimage-thumbnailer']; next action: draft fresh recipe from upstream source in next pass.")
    ("xtest" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['xtest']; next action: draft fresh recipe from upstream source in next pass.")
    ("blacklist-check" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['blacklist-check']; next action: draft fresh recipe from upstream source in next pass.")
    ("fujprog" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['fujprog']; next action: draft fresh recipe from upstream source in next pass.")
    ("oxicord-git" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['oxicord-git', 'oxicord']; next action: draft fresh recipe from upstream source in next pass.")
    ("mev-boost" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['mev-boost']; next action: draft fresh recipe from upstream source in next pass.")
    ("vibe-kanban-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['vibe-kanban-bin', 'vibe-kanban', 'vibekanban']; next action: draft fresh recipe from upstream source in next pass.")
    ("cachyos-service-manager" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['cachyos-service-manager']; next action: draft fresh recipe from upstream source in next pass.")
    ("snapmaker-orca-appimage" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['snapmaker-orca-appimage', 'snapmaker-orca']; next action: draft fresh recipe from upstream source in next pass.")
    ("git-wd40" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['git-wd40']; next action: draft fresh recipe from upstream source in next pass.")
    ("cmc-mod-manager-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['cmc-mod-manager-bin', 'cmc-mod-manager', 'cmcmodmanager']; next action: draft fresh recipe from upstream source in next pass.")
    ("gnome-randr-rust" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['gnome-randr-rust']; next action: draft fresh recipe from upstream source in next pass.")
    ("ethtui" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['ethtui']; next action: draft fresh recipe from upstream source in next pass.")
    ("dmenustatus-git" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['dmenustatus-git', 'dmenustatus']; next action: draft fresh recipe from upstream source in next pass.")
    ("geoclue-tz-bin" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['geoclue-tz-bin', 'geoclue-tz', 'geocluetz']; next action: draft fresh recipe from upstream source in next pass.")
    ("lamco-rdp-server" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['lamco-rdp-server']; next action: draft fresh recipe from upstream source in next pass.")
    ("task-manager" . "NEEDS_RECIPE_DESIGN: guix package index probe found no direct candidate in variants ['task-manager']; next action: draft fresh recipe from upstream source in next pass.")
    ))
